import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { IDIOMAS_DISPONIBLES, type Idioma } from '@/components/ui/SelectorIdioma';

export { IDIOMAS_DISPONIBLES };
export type { Idioma };

const LOCALSTORAGE_KEY = 'idioma_preferido';

interface LanguageState {
  idiomaActual: string;
  setIdioma: (codigo: string) => void;
  idiomaSeleccionado: Idioma;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      idiomaActual: 'ES',
      idiomaSeleccionado: IDIOMAS_DISPONIBLES[0],
      setIdioma: (codigo: string) => {
        const idioma =
          IDIOMAS_DISPONIBLES.find((i) => i.codigo === codigo) || IDIOMAS_DISPONIBLES[0];
        set({ idiomaActual: codigo, idiomaSeleccionado: idioma });
      },
    }),
    {
      name: LOCALSTORAGE_KEY,
      partialize: (state) => ({ idiomaActual: state.idiomaActual }),
    }
  )
);

export const traduccionesUI: Record<string, Record<string, string>> = {
  ES: {
    inicio: 'Inicio',
    cuentos: 'Cuentos',
    sobreNosotros: 'Sobre Nosotros',
    acceder: 'Acceder',
    politicaPrivacidad: 'Política de Privacidad',
    terminosUso: 'Términos de Uso',
    heroTitulo: 'Accesibilidad Cognitiva para Todos',
    heroSubtitulo:
      'Generador de cuentos con Inteligencia Artificial y transcritos a pictogramas para la accesibilidad cognitiva.',
    accederApp: 'CREA UN CUENTO',
    copyright: 'Todos los derechos reservados.',
    enlaces: 'Enlaces',
    legal: 'Legal',
    aceptar: 'Aceptar',
    avisoCookies: 'Utilizamos cookies para mejorar tu experiencia.',
    configTitulo: 'Configuración',
    configIdioma: 'Idioma',
    configIdiomaDesc:
      'Seleccione el idioma de la interfaz. El cambio se aplicará inmediatamente a toda la plataforma.',
    configPrivacidad: 'Privacidad',
    configPoliticaPrivacidad: 'Política de Privacidad',
    configPoliticaCookies: 'Política de Cookies',
    configAvisoLegal: 'Aviso Legal',
    configTerminos: 'Términos de Uso',
    configAcerca: 'Acerca de',
    configDescripcion: 'Plataforma de accesibilidad cognitiva para profesores PT y alumnos.',
    configPrivacidadTitulo: 'Preferencias de Privacidad',
    cookiesAnaliticas: 'Cookies Analíticas',
    cookiesAnaliticasDesc: 'Ayudan a mejorar la herramienta midiendo el uso de forma anónima.',
    cookiesPersonalizacion: 'Cookies de Personalización',
    cookiesPersonalizacionDesc: 'Permiten recordar tu idioma y ajustes en tu próxima visita.',
    cookiesBannerTexto:
      'Utilizamos cookies propias y de terceros para mejorar su experiencia y analizar el uso de la web. Puede aceptar todas las cookies, rechazarlas o configurar sus preferencias.',
    cookiesBannerConfigurar: 'Configurar',
    cookiesBannerEsenciales: 'Solo esenciales',
    cookiesBannerAceptar: 'Aceptar todas',
    cookiesBannerPrivacidad: 'Configuración de Privacidad',
    cookiesBannerNecesarias: 'Necesarias',
    cookiesBannerNecesariasDesc:
      'Permiten el funcionamiento básico de la web como la navegación y la seguridad.',
    cookiesBannerSiempreActivas: 'Siempre activas',
    cookiesBannerAnaliticas: 'Analíticas',
    cookiesBannerAnaliticasDesc:
      'Nos ayudan a entender cómo interactúan los usuarios con la web de forma anónima.',
    cookiesBannerPreferencia: 'Preferencia',
    cookiesBannerPreferenciaDesc:
      'Permiten recordar información para que accedas al servicio con ciertas características (idioma).',
    cookiesBannerVolver: 'Volver atrás',
    cookiesBannerGuardar: 'Guardar preferencias',
    configTextosLegales: 'Textos Legales',
    configTecnologias:
      'Desarrollado con Next.js, TypeScript, Tailwind CSS, Supabase y Google Gemini.',
    cajaSugerencias: 'Caja de sugerencias',
    cajaSugerenciasSubtitulo: 'Envíanos tu opinión o reporta errores',
    cajaPlaceholder: '¿Qué mejorarías?',
    cajaGracias: '¡Gracias!',
    cajaMinimizar: 'Minimizar',
    cajaEnviar: 'Enviar',
    cajaEnviando: 'Enviando...',
    sobreNosotrosTitulo: 'Sobre Nosotros',
    sobreNosotrosMision: 'Nuestra Misión',
    sobreNosotrosMisionTexto:
      'ImaginAC es una plataforma educativa diseñada para facilitar la accesibilidad cognitiva a profesores de educación especial (PT) y alumnos con necesidades específicas de aprendizaje.',
    sobreNosotrosPicto: 'Pictogramas y Recursos Visuales',
    sobreNosotrosPictoTexto:
      'Los pictogramas utilizados en ImaginAC provienen del proyecto ARASAAC (Centro Aragonés de Comunicación Aumentativa y Alternativa), distribuidos bajo licencia Creative Commons.',
    atribucionArasaac: 'Atribución ARASAAC',
    atribucionArasaacTexto:
      'Los símbolos pictográficos utilizados son propiedad del Gobierno de Aragón y han sido creados por Sergio Palao para ARASAAC (http://www.arasaac.org), que los distribuye bajo Licencia Creative Commons BY-NC-SA.',
    deslindeAragon:
      'El Gobierno de Aragón no se hace responsable del uso que terceros hagan de estos materiales.',
    logoArasaacPlaceholder: '[Logo ARASAAC]',
    tecnologias: 'Tecnologías Utilizadas',
    techNextjs: 'Framework web',
    techTypescript: 'Lenguaje tipado',
    techTailwind: 'Estilos',
    techSupabase: 'Base de datos',
    techGemini: 'Inteligencia Artificial',
    techJsPDF: 'Generación de PDFs',
    techArasaac: 'Pictogramas (fuente externa)',
    derechosReservados: 'Todos los derechos reservados.',
    // Sobre Nosotros
    sobreHistoriaTitulo: 'La historia detrás de ImaginAC',
    sobreHistoriaSubtitulo: 'De una necesidad real a una herramienta para todos',
    sobreHistoriaParrafo1:
      'ImaginAC no nació en una oficina, sino en una tarde de café. Escuchaba a una buena amiga, futura docente especializada en Pedagogía Terapéutica (PT), compartir su frustración: a pesar de contar con excelentes bancos de pictogramas, perdía tiempo buscando, recortando y pegando manualmente para crear materiales que se adaptaran a sus alumnos.',
    sobreHistoriaParrafo2:
      'No existía un lugar que le permitiera crear un cuento desde cero y transformarlo, al instante, en un recurso visual listo para imprimir. Como desarrolladora, supe que la tecnología debía llenar ese vacío.',
    sobreHistoriaParrafo3:
      'Si mi amiga se sentía así, miles de docentes estarían pasando por lo mismo. Mi misión hoy es sencilla: que tú solo pongas la imaginación y yo el código. Juntos, creamos materiales inclusivos y profesionales en cuestión de segundos.',
    sobrePerfilTitulo: 'Hola, soy Carmen',
    sobrePerfilDescripcion:
      'Mi nombre completo es Carmen Vicente Crespo. Tras finalizar mi formación como Ingeniera en Tecnologías de Telecomunicación, decidí volcar mi pasión en el desarrollo web, la inteligencia artificial y la ciberseguridad.',
    sobrePerfilDescripcion2:
      'ImaginAC es el resultado de combinar esos conocimientos técnicos con un propósito social: facilitar el día a día de la comunidad educativa mediante herramientas inteligentes.',
    sobreContactoTitulo: '¿Tienes una consulta?',
    sobreContactoDescripcion:
      'Si tienes alguna duda o quieres proponer algo, pulsa el botón para escribirme.',
    sobreContactoBoton: 'Enviar correo',
    terminosTitulo: 'Términos de Uso',
    terminosAceptacion: '1. Aceptación de los Términos',
    terminosAceptacionTexto:
      'Al acceder y utilizar la plataforma ImaginAC, usted acepta estar sujeto a estos Términos de Uso. Si no está de acuerdo con alguno de los términos, no debe utilizar esta plataforma.',
    terminosDescripcion: '2. Descripción del Servicio',
    terminosDescripcionTexto:
      'ImaginAC es una plataforma educativa que proporciona herramientas de accesibilidad cognitiva, incluyendo la generación de cuentos y actividades adaptadas para alumnos con necesidades educativas especiales.',
    terminosUsoAceptable: '3. Uso Aceptable',
    terminosUsoTexto: 'El usuario se compromete a:',
    terminosPropiedad: '4. Propiedad Intelectual',
    terminosPropiedadTexto:
      'Los cuentos y materiales generados mediante la plataforma pueden ser utilizados para fines educativos. Sin embargo, los pictogramas utilizados provienen de ARASAAC y están protegidos por la licencia Creative Commons BY-NC-SA.',
    terminosLimitacion: '5. Limitación de Responsabilidad',
    terminosLimitacionTexto:
      'ImaginAC se proporciona "tal cual". No garantizamos que el servicio sea ininterrumpido o libre de errores. No somos responsables de cualquier daño derivados del uso de la plataforma.',
    terminosModificacion: '6. Modificaciones',
    terminosModificacionTexto:
      'Nos reservamos el derecho de modificar estos términos en cualquier momento. Los cambios entrarán en vigor inmediatamente después de su publicación en la plataforma.',
    terminosContacto: '7. Contacto',
    terminosContactoTexto:
      'Para cualquier pregunta sobre estos Términos de Uso, puede contactarnos a través del formulario de contacto en la plataforma.',
    privacidadTitulo: 'Política de Privacidad',
    privacidadIntro: '1. Introducción',
    privacidadIntroTexto:
      'ImaginAC se compromete a proteger su privacidad. Esta política explica cómo recopilamos, usamos y protegemos su información personal cuando utiliza nuestra plataforma educativa.',
    privacidadDatos: '2. Datos que Recopilamos',
    privacidadUso: '3. Uso de los Datos',
    privacidadUsoTexto: 'Utilizamos sus datos para:',
    privacidadCookies: '4. Cookies',
    privacidadCookiesTexto: 'Utilizamos cookies para:',
    privacidadCookiesAdicional:
      'Para más información sobre nuestra política de cookies, consulte nuestra Política de Cookies.',
    privacidadProteccion: '5. Protección de Datos',
    privacidadProteccionTexto:
      'Implementamos medidas de seguridad apropiadas para proteger sus datos personales contra acceso no autorizado, modificación, divulgación o destrucción. Los datos se almacenan en Supabase con cifrado en tránsito y en reposo.',
    privacidadDerechos: '6. Sus Derechos',
    privacidadDerechosTexto: 'Usted tiene derecho a:',
    privacidadTerceros: '7. Terceros',
    privacidadTercerosTexto:
      'No compartimos sus datos personales con terceros, excepto cuando sea necesario para prestar el servicio o cuando la ley lo exija.',
    privacidadCambios: '8. Cambios',
    privacidadCambiosTexto:
      'Podemos actualizar esta política periódicamente. Le notificaremos cualquier cambio publicando la nueva política en esta página.',
    cuentosTitulo: 'Cuentos Accesibles',
    cuentosDescripcion:
      'Crea cuentos adaptados con pictogramas para facilitar la comprensión y el aprendizaje.',
    cuentosDisponibles: 'Cuentos Disponibles',
    cuentosDisponiblesDesc: 'Inicia sesión para crear y gestionar tus cuentos adaptados.',
    accederCrear: 'Acceder para Crear',
    creditosPicto: 'Créditos de Pictogramas',
    autorPicto: 'Autor pictogramas:',
    origen: 'Origen:',
    licencia: 'Licencia:',
    propiedad: 'Propiedad:',
    gobiernoAragon: 'Gobierno de Aragón (España)',
    atribucionFooter: 'Autor: Sergio Palao. Origen: ARASAAC. Licencia: CC BY-NC-SA',
    pictogramas: 'Pictogramas',
    formTituloCuento: 'Título del cuento',
    formPlaceholderTitulo: 'El dragón que tenía miedo',
    formTematica: 'Temática',
    formSelectTematica: 'Selecciona una temática',
    formFinalidad: 'Finalidad pedagógica',
    formPlaceholderFinalidad:
      'Este cuento ayuda al niño a identificar y expresar el miedo, fomentando la comprensión de que es normal sentir miedo y que hay estrategias para superarlo.',
    formCaracteres: 'caracteres',
    formLongitud: 'Longitud del cuento',
    formCorto: 'Corto',
    formMedio: 'Medio',
    formLargo: 'Largo',
    formPalabras: 'palabras',
    formResumen: 'Resumen de la generación',
    formLabelTitulo: 'Título',
    formLabelTematica: 'Temática',
    formLabelIdioma: 'Idioma',
    formLabelLongitud: 'Longitud',
    formSinDefinir: 'Sin definir',
    formGenerando: 'Generando cuento...',
    formBotonGenerar: 'Generar Cuento con Pictogramas',
    formPalabras100: '100 palabras',
    formPalabras200: '200 palabras',
    formPalabras300: '300 palabras',
  },
  EN: {
    inicio: 'Home',
    cuentos: 'Stories',
    sobreNosotros: 'About Us',
    acceder: 'Login',
    politicaPrivacidad: 'Privacy Policy',
    terminosUso: 'Terms of Use',
    heroTitulo: 'Cognitive Accessibility for Everyone',
    heroSubtitulo:
      'Story generator with Artificial Intelligence and transcribed into pictograms for cognitive accessibility.',
    accederApp: 'CREATE A STORY',
    copyright: 'All rights reserved.',
    enlaces: 'Links',
    legal: 'Legal',
    aceptar: 'Accept',
    avisoCookies: 'We use cookies to improve your experience.',
    configTitulo: 'Settings',
    configIdioma: 'Language',
    configIdiomaDesc: 'Select the interface language. Changes apply immediately.',
    configPrivacidad: 'Privacy',
    configPoliticaPrivacidad: 'Privacy Policy',
    configPoliticaCookies: 'Cookies Policy',
    configAvisoLegal: 'Legal Notice',
    configTerminos: 'Terms of Use',
    configAcerca: 'About',
    configDescripcion:
      'Cognitive accessibility platform for special education teachers and students.',
    configPrivacidadTitulo: 'Privacy Preferences',
    cookiesAnaliticas: 'Analytics Cookies',
    cookiesAnaliticasDesc: 'They help improve the tool by measuring usage anonymously.',
    cookiesPersonalizacion: 'Customization Cookies',
    cookiesPersonalizacionDesc:
      'They allow remembering your language and settings on your next visit.',
    cookiesBannerTexto:
      'We use own and third-party cookies to improve your experience and analyze web usage. You can accept all cookies, reject them, or configure your preferences.',
    cookiesBannerConfigurar: 'Configure',
    cookiesBannerEsenciales: 'Only essential',
    cookiesBannerAceptar: 'Accept all',
    cookiesBannerPrivacidad: 'Privacy Settings',
    cookiesBannerNecesarias: 'Necessary',
    cookiesBannerNecesariasDesc: 'They allow basic web functioning like navigation and security.',
    cookiesBannerSiempreActivas: 'Always active',
    cookiesBannerAnaliticas: 'Analytics',
    cookiesBannerAnaliticasDesc:
      'They help us understand how users interact with the website anonymously.',
    cookiesBannerPreferencia: 'Preference',
    cookiesBannerPreferenciaDesc:
      'Allow remembering information so you access the service with certain features (language).',
    cookiesBannerVolver: 'Go back',
    cookiesBannerGuardar: 'Save preferences',
    configTextosLegales: 'Legal Texts',
    configTecnologias:
      'Developed with Next.js, TypeScript, Tailwind CSS, Supabase and Google Gemini.',
    cajaSugerencias: 'Suggestions box',
    cajaSugerenciasSubtitulo: 'Send us your feedback or report errors',
    cajaPlaceholder: 'What would you improve?',
    cajaGracias: 'Thank you!',
    cajaMinimizar: 'Minimize',
    cajaEnviar: 'Send',
    cajaEnviando: 'Sending...',
    sobreNosotrosTitulo: 'About Us',
    sobreNosotrosMision: 'Our Mission',
    sobreNosotrosMisionTexto:
      'ImaginAC is an educational platform designed to facilitate cognitive accessibility for special education teachers and students with specific learning needs.',
    sobreNosotrosPicto: 'Pictograms and Visual Resources',
    sobreNosotrosPictoTexto:
      'The pictograms used in ImaginAC come from the ARASAAC project, distributed under Creative Commons license.',
    atribucionArasaac: 'ARASAAC Attribution',
    atribucionArasaacTexto:
      'The pictographic symbols used are property of the Government of Aragon and were created by Sergio Palao for ARASAAC (http://www.arasaac.org), distributed under Creative Commons BY-NC-SA license.',
    deslindeAragon:
      'The Government of Aragon is not responsible for the use third parties make of these materials.',
    sobreHistoriaTitulo: 'The story behind ImaginAC',
    sobreHistoriaSubtitulo: 'From a real need to a tool for everyone',
    sobreHistoriaParrafo1:
      "ImaginAC wasn't born in an office, but over a coffee afternoon. I listened to a good friend, a future specialized teacher in Therapeutic Pedagogy (PT), share her frustration: despite having excellent pictogram banks, she spent time searching, cutting and pasting manually to create materials tailored to her students.",
    sobreHistoriaParrafo2:
      'There was no place that allowed her to create a story from scratch and transform it, instantly, into a ready-to-print visual resource. As a developer, I knew technology had to fill that void.',
    sobreHistoriaParrafo3:
      'If my friend felt this way, thousands of teachers would be going through the same thing. My mission today is simple: you provide the imagination and I provide the code. Together, we create inclusive and professional materials in seconds.',
    sobrePerfilTitulo: "Hello, I'm Carmen",
    sobrePerfilDescripcion:
      'My full name is Carmen Vicente Crespo. After finishing my training as a Telecommunications Technology Engineer, I decided to focus my passion on web development, artificial intelligence and cybersecurity.',
    sobrePerfilDescripcion2:
      'ImaginAC is the result of combining these technical skills with a social purpose: facilitating the daily life of the educational community through intelligent tools.',
    sobreContactoTitulo: 'Do you have a question?',
    sobreContactoDescripcion:
      'If you have any doubts or want to propose something, click the button to write to me.',
    sobreContactoBoton: 'Send email',
    tecnologias: 'Technologies Used',
    techNextjs: 'Web framework',
    techTypescript: 'Typed language',
    techTailwind: 'Styles',
    techSupabase: 'Database',
    techGemini: 'Artificial Intelligence',
    techJsPDF: 'PDF generation',
    techArasaac: 'Pictograms (external source)',
    derechosReservados: 'All rights reserved.',
    terminosTitulo: 'Terms of Use',
    terminosAceptacion: '1. Acceptance of Terms',
    terminosAceptacionTexto:
      'By accessing and using the ImaginAC platform, you agree to be bound by these Terms of Use.',
    terminosDescripcion: '2. Service Description',
    terminosDescripcionTexto:
      'ImaginAC is an educational platform providing cognitive accessibility tools including story generation and adapted activities.',
    terminosUsoAceptable: '3. Acceptable Use',
    terminosUsoTexto: 'The user agrees to:',
    terminosPropiedad: '4. Intellectual Property',
    terminosPropiedadTexto:
      'Stories and materials generated may be used for educational purposes. Pictograms are from ARASAAC under CC BY-NC-SA license.',
    terminosLimitacion: '5. Limitation of Liability',
    terminosLimitacionTexto:
      'ImaginAC is provided "as is". We are not responsible for damages from using the platform.',
    terminosModificacion: '6. Modifications',
    terminosModificacionTexto: 'We reserve the right to modify these terms at any time.',
    terminosContacto: '7. Contact',
    terminosContactoTexto: 'For questions about these terms, contact us through the platform.',
    privacidadTitulo: 'Privacy Policy',
    privacidadIntro: '1. Introduction',
    privacidadIntroTexto:
      'ImaginAC is committed to protecting your privacy. This policy explains how we collect, use and protect your personal information.',
    privacidadDatos: '2. Data We Collect',
    privacidadUso: '3. Use of Data',
    privacidadUsoTexto: 'We use your data to:',
    privacidadCookies: '4. Cookies',
    privacidadCookiesTexto: 'We use cookies to:',
    privacidadCookiesAdicional: 'For more information about cookies, see our Cookie Policy.',
    privacidadProteccion: '5. Data Protection',
    privacidadProteccionTexto:
      'We implement appropriate security measures to protect your personal data.',
    privacidadDerechos: '6. Your Rights',
    privacidadDerechosTexto: 'You have the right to:',
    privacidadTerceros: '7. Third Parties',
    privacidadTercerosTexto:
      'We do not share personal data except when necessary to provide the service.',
    privacidadCambios: '8. Changes',
    privacidadCambiosTexto: 'We may update this policy periodically.',
    cuentosTitulo: 'Accessible Stories',
    cuentosDescripcion: 'Create adapted stories with pictograms.',
    cuentosDisponibles: 'Available Stories',
    cuentosDisponiblesDesc: 'Sign in to create and manage your adapted stories.',
    accederCrear: 'Sign in to Create',
    creditosPicto: 'Pictogram Credits',
    autorPicto: 'Pictogram author:',
    origen: 'Origin:',
    licencia: 'License:',
    propiedad: 'Property:',
    gobiernoAragon: 'Government of Aragon (Spain)',
    atribucionFooter: 'Author: Sergio Palao. Origin: ARASAAC. License: CC BY-NC-SA',
    pictogramas: 'Pictograms',
    formTituloCuento: 'Story title',
    formPlaceholderTitulo: 'The dragon who was afraid',
    formTematica: 'Theme',
    formSelectTematica: 'Select a theme',
    formFinalidad: 'Pedagogical purpose',
    formPlaceholderFinalidad:
      'This story helps the child identify and express fear, promoting understanding that it is normal to feel afraid.',
    formCaracteres: 'characters',
    formLongitud: 'Story length',
    formCorto: 'Short',
    formMedio: 'Medium',
    formLargo: 'Long',
    formPalabras: 'words',
    formResumen: 'Generation summary',
    formLabelTitulo: 'Title',
    formLabelTematica: 'Theme',
    formLabelIdioma: 'Language',
    formLabelLongitud: 'Length',
    formSinDefinir: 'Undefined',
    formGenerando: 'Generating story...',
    formBotonGenerar: 'Generate Story with Pictograms',
    formPalabras100: '100 words',
    formPalabras200: '200 words',
    formPalabras300: '300 words',
  },
  CA: {
    inicio: 'Inici',
    cuentos: 'Contes',
    sobreNosotros: 'Sobre Nosaltres',
    acceder: 'Accedir',
    politicaPrivacidad: 'Política de Privacitat',
    terminosUso: "Termes d'Ús",
    heroTitulo: 'Accessibilitat Cognitiva per a Tots',
    heroSubtitulo:
      "Eines educatives dissenyades per a professors PT i alumnes amb necessitats específiques d'aprenentatge.",
    accederApp: "Accedir a l'App",
    copyright: 'Tots els drets reservats.',
    sobreHistoriaTitulo: "La història darrere d'ImaginAC",
    sobreHistoriaSubtitulo: "D'una necessitat real a una eina per a tothom",
    sobreHistoriaParrafo1:
      "ImaginAC no va néixer en una oficina, sinó en una tarda de cafè. Escoltava una bona amiga, futura docent especialitzada en Pedagogia Terapèutica (PT), compartir la seva frustració: tot i disposar d'excel·lents bancs de pictogrames, perdia temps cercant, retallant i enganxint manualment per crear materials que s'adaptessin als seus alumnes.",
    sobreHistoriaParrafo2:
      "No existia un lloc que li permetés crear un conte des de zero i transformar-lo, a l'instant, en un recurs visual llest per imprimir. Com a desenvolupadora, vaig saber que la tecnologia havia d'omplir aquest buit.",
    sobreHistoriaParrafo3:
      'Si la meva amiga se sentia així, milers de docents estarien passant el mateix. La meva missió avui és senzilla: tu posa la imaginació i jo el codi. Junts, creem materials inclusius i professionals en qüestió de segons.',
    sobrePerfilTitulo: 'Hola, sóc Carmen',
    sobrePerfilDescripcion:
      'El meu nom complet és Carmen Vicente Crespo. Després de finalitzar la meva formació com a Enginyera en Tecnologies de Telecomunicació, vaig decidir dedicar la meva passió al desenvolupament web, la intel·ligència artificial i la ciberseguretat.',
    sobrePerfilDescripcion2:
      'ImaginAC és el resultat de combinar aquests coneixements tècnics amb un propòsit social: facilitar el dia a dia de la comunitat educativa mitjançant eines intel·ligents.',
    sobreContactoTitulo: 'Tens una consulta?',
    sobreContactoDescripcion:
      "Si tens alguna dubte o vols proposar alguna cosa, prem el botó per escriure'm.",
    sobreContactoBoton: 'Enviar correu',
    enlaces: 'Enllaços',
    legal: 'Legal',
    aceptar: 'Acceptar',
    avisoCookies: 'Utilitzem cookies per millorar la teva experiència.',
    configTitulo: 'Configuració',
    configIdioma: 'Idioma',
    configIdiomaDesc:
      "Seleccioneu l'idioma de la interfície. El canvi s'aplicarà immediatament a tota la plataforma.",
    configPrivacidad: 'Privacitat',
    configPoliticaPrivacidad: 'Política de Privacitat',
    configTerminos: "Termes d'Ús",
    configAcerca: 'Quant a',
    configDescripcion: "Plataforma d'accessibilitat cognitiva per a professors PT i alumnes.",
    configPrivacidadTitulo: 'Preferències de Privacitat',
    cookiesAnaliticas: 'Cookies Analítiques',
    cookiesAnaliticasDesc: 'Ajuden a millorar eina mesurant ús de manera anònima.',
    cookiesPersonalizacion: 'Cookies de Personalització',
    cookiesPersonalizacionDesc: 'Permeten recordar idioma i ajustos a propera visita.',
    cookiesBannerTexto:
      "Utilitzem cookies pròpies i de tercers per millorar la teva experiència i analitzar l'ús del lloc web. Pots acceptar totes les cookies, refusar-les o configurar les teves preferències.",
    cookiesBannerConfigurar: 'Configurar',
    cookiesBannerEsenciales: 'Només essencials',
    cookiesBannerAceptar: 'Acceptar totes',
    cookiesBannerPrivacidad: 'Configuració de Privacitat',
    cookiesBannerNecesarias: 'Necessàries',
    cookiesBannerNecesariasDesc:
      'Permeten el funcionament bàsic del lloc web com la navegació i la seguretat.',
    cookiesBannerSiempreActivas: 'Sempre actives',
    cookiesBannerAnaliticas: 'Analítiques',
    cookiesBannerAnaliticasDesc:
      'Ens ajuden a entendre com interaccionen els usuaris amb el lloc web de forma anònima.',
    cookiesBannerPreferencia: 'Preferència',
    cookiesBannerPreferenciaDesc:
      'Permeten recorda informació perquè accedisques al servei amb determinades característiques (idioma).',
    cookiesBannerVolver: 'Tornar enrere',
    cookiesBannerGuardar: 'Guardar preferències',
    configTextosLegals: 'Textos Legals',
    configTecnologias:
      'Desenvolupat amb Next.js, TypeScript, Tailwind CSS, Supabase i Google Gemini.',
    cajaSugerencias: 'Caixa de suggeriments',
    cajaSugerenciasSubtitulo: "Envia'ns la teva opinió o informa d'errors",
    cajaPlaceholder: 'Què milloraries?',
    cajaGracias: 'Gràcies!',
    cajaMinimizar: 'Minimitzar',
    cajaEnviar: 'Enviar',
    cajaEnviando: 'Enviant...',
    sobreNosotrosTitulo: 'Sobre Nosaltres',
    sobreNosotrosMision: 'La Nostra Missió',
    sobreNosotrosMisionTexto:
      "ImaginAC és una plataforma educativa dissenyada per facilitar l'accessibilitat cognitiva a professors d'educació especial i alumnes amb necessitats específiques d'aprenentatge.",
    sobreNosotrosPicto: 'Pictogrames i Recursos Visuals',
    sobreNosotrosPictoTexto:
      'Els pictogrames utilitzats a ImaginAC provenen del projecte ARASAAC, distribuïts sota llicència Creative Commons.',
    atribucionArasaac: 'Atribució ARASAAC',
    atribucionArasaacTexto:
      "Els simbols pictogràfics utilitzats són propietat del Govern d'Aragó i han estat creats per Sergio Palao per a ARASAAC (http://www.arasaac.org), distribuïts sota Llicència Creative Commons BY-NC-SA.",
    deslindeAragon:
      "El Govern d'Aragó no es fa responsable de l'ús que tercers facin d'aquests materials.",
    tecnologias: 'Tecnologies Utilitzades',
    techNextjs: 'Framework web',
    techTypescript: 'Llenguatge tipat',
    techTailwind: 'Estils',
    techSupabase: 'Base de dades',
    techGemina: 'Intel·ligència Artificial',
    techJsPDF: 'Generació de PDFs',
    techArasaac: 'Pictogrames (font externa)',
    derechosReservados: 'Tots els drets reservats.',
    terminosTitulo: "Termes d'Ús",
    terminosAceptacion: '1. Acceptació dels Termes',
    terminosAceptacionTexto:
      "En accedir i utilitzar la plataforma ImaginAC, vostè accepta estar subjecte a aquests Termes d'Ús.",
    terminosDescripcion: '2. Descripció del Servei',
    terminosDescripcionTexto:
      "ImaginAC és una plataforma educativa que proporciona eines d'accessibilitat cognitiva, inclosa la generació de contes i activitats adaptades.",
    terminosUsoAceptable: '3. Ús Acceptable',
    terminosUsoTexto: "L'usuari es compromet a:",
    terminosPropiedad: '4. Propietat Intel·lectual',
    terminosPropiedadTexto:
      "Els contes i materials generats poden ser utilitzats per a finalitats educatives. Els pictogrames provenen d'ARASAAC amb llicència CC BY-NC-SA.",
    terminosLimitacion: '5. Limitació de Responsabilitat',
    terminosLimitacionTexto:
      'ImaginAC es proporciona "tal qual". No som responsables de danys derivats de l\'ús de la plataforma.',
    terminosModificacion: '6. Modificacions',
    terminosModificacionTexto:
      'Ens reservem el dret de modificar aquests termes en qualsevol moment.',
    terminosContacto: '7. Contacte',
    terminosContactoTexto:
      "Per a qualsevol pregunta sobre aquests Termes d'Ús, podeu contactar-nos a través de la plataforma.",
    privacidadTitulo: 'Política de Privacitat',
    privacidadIntro: '1. Introducció',
    privacidadIntroTexto:
      'ImaginAC es compromet a protegir la vostra privacitat. Aquesta política explica com recopilem, utilitzem i protegim la vostra informació personal.',
    privacidadDatos: '2. Dades que Recopilem',
    privacidadUso: '3. Ús de les Dades',
    privacidadUsoTexto: 'Utilitzem les vostres dades per:',
    privacidadCookies: '4. Cookies',
    privacidadCookiesTexto: 'Utilitzem cookies per:',
    privacidadCookiesAdicional:
      'Per a més informació sobre cookies, consulteu la nostra Política de Cookies.',
    privacidadProteccion: '5. Protecció de Dades',
    privacidadProteccionTexto:
      'Implementem mesures de seguretat apropiades per protegir les vostres dades personals.',
    privacidadDerechos: '6. Els Vostres Drets',
    privacidadDerechosTexto: 'Teniu dret a:',
    privacidadTerceros: '7. Tercers',
    privacidadTercerosTexto:
      'No compartim dades personals excepte quan sigui necessari per prestar el servei.',
    privacidadCambios: '8. Canvis',
    privacidadCambiosTexto: 'Podem actualitzar aquesta política periòdicament.',
    cuentosTitulo: 'Contes Accesibles',
    cuentosDescripcion: 'Crea contes adaptats amb pictogrames.',
    cuentosDisponibles: 'Contes Disponibles',
    cuentosDisponiblesDesc: 'Inicieu sessió per crear i gestionar els vostres contes adaptats.',
    accederCrear: 'Iniciar sessió per Crear',
    creditosPicto: 'Crèdits de Pictogrames',
    autorPicto: 'Autor pictogrames:',
    origen: 'Origen:',
    licencia: 'Llicència:',
    propiedad: 'Propietat:',
    gobiernoAragon: "Govern d'Aragó (Espanya)",
    atribucionFooter: 'Autor: Sergio Palao. Origen: ARASAAC. Llicència: CC BY-NC-SA',
    pictogramas: 'Pictogrames',
    formTituloCuento: 'Títol del conte',
    formPlaceholderTitulo: 'El drac que tenia por',
    formTematica: 'Temàtica',
    formSelectTematica: 'Selecciona una temàtica',
    formFinalidad: 'Finalitat pedagògica',
    formPlaceholderFinalidad:
      'Aquest conte ajuda al nen a identificar i expressar la por, promovent la comprensió que és normal tenir por.',
    formCaracteres: 'caràcters',
    formLongitud: 'Longitud del conte',
    formCorto: 'Curt',
    formMedio: 'Mig',
    formLargo: 'Llarg',
    formPalabras: 'paraules',
    formResumen: 'Resum de la generació',
    formLabelTitulo: 'Títol',
    formLabelTematica: 'Temàtica',
    formLabelIdioma: 'Idioma',
    formLabelLongitud: 'Longitud',
    formSinDefinir: 'Sense definir',
    formGenerando: 'Generant conte...',
    formBotonGenerar: 'Generar Conte amb Pictogrames',
    formPalabras100: '100 paraules',
    formPalabras200: '200 paraules',
    formPalabras300: '300 paraules',
  },
  VA: {
    inicio: 'Inici',
    cuentos: 'Contes',
    sobreNosotros: 'Sobre Nosaltres',
    acceder: 'Accedir',
    politicaPrivacidad: 'Política de Privacitat',
    terminosUso: "Termes d'Ús",
    heroTitulo: 'Accessibilitat Cognitiva per a Tots',
    heroSubtitulo:
      "Eines educatives dissenyades per a professors PT i alumnes amb necessitats específiques d'aprenentatge.",
    accederApp: "Accedir a l'App",
    copyright: 'Tots els drets reservats.',
    sobreHistoriaTitulo: "La història darrere d'ImaginAC",
    sobreHistoriaSubtitulo: "D'una necessitat real a una eina per a tothom",
    sobreHistoriaParrafo1:
      "ImaginAC no va néixer en una oficina, sinó en una tarda de cafè. Escoltava una bona amiga, futura docent especialitzada en Pedagogia Terapèutica (PT), compartir la seva frustració: tot i disposar d'excel·lents bancs de pictogrames, perdia temps cercant, retallant i enganxint manualment per crear materials que s'adaptessin als seus alumnes.",
    sobreHistoriaParrafo2:
      "No existia un lloc que li permetés crear un conte des de zero i transformar-lo, a l'instant, en un recurs visual llest per imprimir. Com a desenvolupadora, vaig saber que la tecnologia havia d'omplir aquest buit.",
    sobreHistoriaParrafo3:
      'Si la meva amiga se sentia així, milers de docents estarien passant el mateix. La meva missió avui és senzilla: tu posa la imaginació i jo el codi. Junts, creem materials inclusius i professionals en qüestió de segons.',
    sobrePerfilTitulo: 'Hola, sóc Carmen',
    sobrePerfilDescripcion:
      'El meu nom complet és Carmen Vicente Crespo. Després de finalitzar la meva formació com a Enginyera en Tecnologies de Telecomunicació, vaig decidir dedicar la meva passió al desenvolupament web, la intel·ligència artificial i la ciberseguretat.',
    sobrePerfilDescripcion2:
      'ImaginAC és el resultat de combinar aquests coneixements tècnics amb un propòsit social: facilitar el dia a dia de la comunitat educativa mitjançant eines intel·ligents.',
    sobreContactoTitulo: 'Tens una consulta?',
    sobreContactoDescripcion:
      "Si tens alguna dubte o vols proposar alguna cosa, prem el botó per escriure'm.",
    sobreContactoBoton: 'Enviar correu',
    enlaces: 'Enllaços',
    legal: 'Legal',
    aceptar: 'Acceptar',
    avisoCookies: 'Utilitzem cookies per millorar la teva experiència.',
    configTitulo: 'Configuració',
    configIdioma: 'Idioma',
    configIdiomaDesc:
      "Seleccioneu l'idioma de la interfície. El canvi s'aplicarà immediatament a tota la plataforma.",
    configPrivacidad: 'Privacitat',
    configPoliticaPrivacidad: 'Política de Privacitat',
    configTerminos: "Termes d'Ús",
    configAcerca: 'Quant a',
    configDescripcion: "Plataforma d'accessibilitat cognitiva per a professors PT i alumnes.",
    configPrivacidadTitulo: 'Preferències de Privacitat',
    cookiesAnaliticas: 'Cookies Analítiques',
    cookiesAnaliticasDesc: 'Ajuden a millorar eina mesurant ús de manera anònima.',
    cookiesPersonalizacion: 'Cookies de Personalització',
    cookiesPersonalizacionDesc: 'Permeten recordar idioma i ajustos a propera visita.',
    cookiesBannerTexto:
      "Utilitzem cookies pròpies i de tercers per millorar la teva experiència i analitzar l'ús del lloc web. Pots acceptar totes les cookies, refusar-les o configurar les teves preferències.",
    cookiesBannerConfigurar: 'Configurar',
    cookiesBannerEsenciales: 'Només essencials',
    cookiesBannerAceptar: 'Acceptar totes',
    cookiesBannerPrivacidad: 'Configuració de Privacitat',
    cookiesBannerNecesarias: 'Necessàries',
    cookiesBannerNecesariasDesc:
      'Permeten el funcionament bàsic del lloc web com la navegació i la seguretat.',
    cookiesBannerSiempreActivas: 'Sempre actives',
    cookiesBannerAnaliticas: 'Analítiques',
    cookiesBannerAnaliticasDesc:
      'Ens ajuden a entendre com interaccionen els usuaris amb el lloc web de forma anònima.',
    cookiesBannerPreferencia: 'Preferència',
    cookiesBannerPreferenciaDesc:
      'Permeten recorda informació perquè accedisques al servei amb determinades característiques (idioma).',
    cookiesBannerVolver: 'Tornar enrere',
    cookiesBannerGuardar: 'Guardar preferències',
    configTextosLegales: 'Textos Legals',
    configTecnologias:
      'Desenvolupat amb Next.js, TypeScript, Tailwind CSS, Supabase i Google Gemini.',
    cajaSugerencias: 'Caixa de suggeriments',
    cajaSugerenciasSubtitulo: "Envia'ns la teva opinió o reporta errors",
    cajaPlaceholder: 'Què milloraries?',
    cajaGracias: 'Gràcies!',
    cajaMinimizar: 'Minimitzar',
    cajaEnviar: 'Enviar',
    cajaEnviando: 'Enviant...',
    sobreNosotrosTitulo: 'Sobre Nosaltres',
    sobreNosotrosMision: 'La Nostra Missió',
    sobreNosotrosMisionTexto:
      "ImaginAC és una plataforma educativa dissenyada per facilitar l'accessibilitat cognitiva a professors PT i alumnes.",
    sobreNosotrosPicto: 'Pictogrames i Recursos Visuals',
    sobreNosotrosPictoTexto: 'Els pictogrames utilitzats a ImaginAC provenen del projecte ARASAAC.',
    atribucionArasaac: 'Atribució ARASAAC',
    atribucionArasaacTexto:
      "Els simbols pictogràfics utilitzats són propietat del Govern d'Aragó i han estat creats per Sergio Palao per a ARASAAC (http://www.arasaac.org) sota Llicència Creative Commons BY-NC-SA.",
    deslindeAragon:
      "El Govern d'Aragó no es fa responsable de l'ús que tercers facin d'aquests materials.",
    tecnologias: 'Tecnologies Utilitzades',
    techNextjs: 'Framework web',
    techTypescript: 'Llenguatge tipat',
    techTailwind: 'Estils',
    techSupabase: 'Base de dades',
    techGemina: 'Intel·ligència Artificial',
    techJsPDF: 'Generació de PDFs',
    techArasaac: 'Pictogrames (font externa)',
    derechosReservados: 'Tots els drets reservats.',
    terminosTitulo: "Termes d'Ús",
    terminosAceptacion: '1. Acceptació dels Termes',
    terminosAceptacionTexto:
      "En accedir i utilitzar la plataforma ImaginAC, accepteu estar subjecte a aquests Termes d'Ús.",
    terminosDescripcion: '2. Descripció del Servei',
    terminosDescripcionTexto:
      "ImaginAC és una plataforma educativa que proporciona eines d'accessibilitat cognitiva.",
    terminosUsoAceptable: '3. Ús Acceptable',
    terminosUsoTexto: "L'usuari es compromet a:",
    terminosPropiedad: '4. Propietat Intel·lectual',
    terminosPropiedadTexto: "Els pictogrames provenen d'ARASAAC amb llicència CC BY-NC-SA.",
    terminosLimitacion: '5. Limitació de Responsabilitat',
    terminosLimitacionTexto: 'ImaginAC es proporciona "tal qual".',
    terminosModificacion: '6. Modificacions',
    terminosModificacionTexto: 'Ens reservem el dret de modificar aquests termes.',
    terminosContacto: '7. Contacte',
    terminosContactoTexto: 'Per a preguntes sobre aquests Termes, contacteu-nos.',
    privacidadTitulo: 'Política de Privacitat',
    privacidadIntro: '1. Introducció',
    privacidadIntroTexto: 'ImaginAC es compromet a protegir la vostra privacitat.',
    privacidadDatos: '2. Dades que Recopilem',
    privacidadUso: '3. Ús de les Dades',
    privacidadUsoTexto: 'Utilitzem les vostres dades per:',
    privacidadCookies: '4. Cookies',
    privacidadCookiesTexto: 'Utilitzem cookies per:',
    privacidadCookiesAdicional: 'Consulteu la nostra Política de Cookies.',
    privacidadProteccion: '5. Protecció de Dades',
    privacidadProteccionTexto: 'Implementem mesures de seguretat per protegir les vostres dades.',
    privacidadDerechos: '6. Els Vostres Drets',
    privacidadDerechosTexto: 'Teniu dret a:',
    privacidadTerceros: '7. Tercers',
    privacidadTercerosTexto: 'No compartim dades personals excepte quan siga necessari.',
    privacidadCambios: '8. Canvis',
    privacidadCambiosTexto: 'Podem actualitzar aquesta política periòdicament.',
    cuentosTitulo: 'Contes Accesibles',
    cuentosDescripcion: 'Crea contes adaptats amb pictogrames.',
    cuentosDisponibles: 'Contes Disponibles',
    cuentosDisponiblesDesc: 'Inicieu sessió per crear i gestionar els vostres contes.',
    accederCrear: 'Iniciar sessió per Crear',
    creditosPicto: 'Crèdits de Pictogrames',
    autorPicto: 'Autor pictogrames:',
    origen: 'Origen:',
    licencia: 'Llicència:',
    propiedad: 'Propietat:',
    gobiernoAragon: "Govern d'Aragó (Espanya)",
    atribucionFooter: 'Autor: Sergio Palao. Origen: ARASAAC. Llicència: CC BY-NC-SA',
    pictogramas: 'Pictogrames',
    formTituloCuento: 'Títol del conte',
    formPlaceholderTitulo: 'El drac que tenía por',
    formTematica: 'Temàtica',
    formSelectTematica: 'Selecciona una temàtica',
    formFinalidad: 'Finalitat pedagògica',
    formPlaceholderFinalidad: 'Aquest conte ajuda el xiquet a identificar la por.',
    formCaracteres: 'caràcters',
    formLongitud: 'Longitud del conte',
    formCorto: 'Curt',
    formMedio: 'Mig',
    formLargo: 'Llarg',
    formPalabras: 'paraules',
    formResumen: 'Resum de la generació',
    formLabelTitulo: 'Títol',
    formLabelTematica: 'Temàtica',
    formLabelIdioma: 'Idioma',
    formLabelLongitud: 'Longitud',
    formSinDefinir: 'Sense definir',
    formGenerando: 'Generant conte...',
    formBotonGenerar: 'Generar Conte amb Pictogrames',
    formPalabras100: '100 paraules',
    formPalabras200: '200 paraules',
    formPalabras300: '300 paraules',
  },
  GL: {
    inicio: 'Inicio',
    cuentos: 'Contos',
    sobreNosotros: 'Sobre Nós',
    acceder: 'Acceder',
    politicaPrivacidad: 'Política de Privacidade',
    terminosUso: 'Termos de Uso',
    heroTitulo: 'Accesibilidade Cognitiva para Todos',
    heroSubtitulo:
      'Ferramentas educativas deseñadas para profesores PT e alumnos con necesidades específicas de aprendizaxe.',
    accederApp: 'Acceder á App',
    copyright: 'Todos os dereitos reservados.',
    sobreHistoriaTitulo: 'A historia detrás de ImaginAC',
    sobreHistoriaSubtitulo: 'Dunha necesidade real a unha ferramenta para todos',
    sobreHistoriaParrafo1:
      'ImaginAC non nacéu nunha oficina, senón nunha tarde de café. Escoitaba a unha boa amiga, futura docente especializada en Pedagoxía Terapéutica (PT), compartir a súa frustración: a pesar de contar con excelentes bancos de pictogramas, perdía tempo buscando, recortando e pegando manualmente para crear materiais que se adaptaran aos seus alumnos.',
    sobreHistoriaParrafo2:
      'Non existía un lugar que lle permitise crear un conto desde cero e transformalo, instantaneamente, nun recurso visual listo para imprimir. Como desenvolvedora, souben que a tecnología debía encher ese baleiro.',
    sobreHistoriaParrafo3:
      'Se a miña amiga se sentía así, miles de docentes estarían pasando polo mesmo. A miña misión hoxe é sinxela: ti pon a imaxinación e eu o código. Xuntos, creamos materiais inclusivos e profesionais en cuestión de segundos.',
    sobrePerfilTitulo: 'Hola, son Carmen',
    sobrePerfilDescripcion:
      'O meu nome completo é Carmen Vicente Crespo. Tras finalizar a miña formación como Enxeñeira en Tecnoloxías de Telecomunicación, decidín doar a miña pasión ao desenvolvemento web, a intelixencia artificial e a ciberseguridade.',
    sobrePerfilDescripcion2:
      'ImaginAC é o resultado de combinar estes coñecementos técnicos cun propósito social: facilitar o día a día da comunidade educativa mediante ferramentas intelixentes.',
    sobreContactoTitulo: 'Tes unha consulta?',
    sobreContactoDescripcion:
      'Se tes algún dúbida ou queres propoñer algo, preme o botón para escribirme.',
    sobreContactoBoton: 'Enviar correo',
    enlaces: 'Ligazóns',
    legal: 'Legal',
    aceptar: 'Aceptar',
    avisoCookies: 'Usamos cookies para mellorar a túa experiencia.',
    configTitulo: 'Configuración',
    configIdioma: 'Idioma',
    configIdiomaDesc: 'Seleccione o idioma da interface. A cambio aplicarase inmediatamente.',
    configPrivacidad: 'Privacidade',
    configPoliticaPrivacidad: 'Política de Privacidade',
    configPoliticaCookies: 'Política de Cookies',
    configAvisoLegal: 'Aviso Legal',
    configTerminos: 'Termos de Uso',
    configAcerca: 'Acerca de',
    configDescripcion: 'Plataforma de accesibilidade cognitiva para profesores PT e alumnos.',
    configPrivacidadTitulo: 'Preferencias de Privacidade',
    cookiesAnaliticas: 'Cookies Analíticas',
    cookiesAnaliticasDesc: 'Axudan a mellorar a ferramenta metricando uso de xeito anónimo.',
    cookiesPersonalizacion: 'Cookies de Personalización',
    cookiesPersonalizacionDesc: 'Permiten recordar idioma e axustes na túa seguinte visita.',
    cookiesBannerTexto:
      'Empregamos cookies propias e de terceiros para mellorar a túa experiencia e analizar o uso da web. Podes.acceptar todas as cookies, refusalas ou configurar as túas preferencias.',
    cookiesBannerConfigurar: 'Configurar',
    cookiesBannerEsenciales: 'Só esenciais',
    cookiesBannerAceptar: 'Aceptar todas',
    cookiesBannerPrivacidad: 'Configuración de Privacidade',
    cookiesBannerNecesarias: 'Necesarias',
    cookiesBannerNecesariasDesc:
      'Permiten o funcionamento básico da web como a navegación e a seguridade.',
    cookiesBannerSiempreActivas: 'Sempre activas',
    cookiesBannerAnaliticas: 'Analíticas',
    cookiesBannerAnaliticasDesc:
      'Axúdannos a entender como interactúan os usuarios coa web de forma anónima.',
    cookiesBannerPreferencia: 'Preferencia',
    cookiesBannerPreferenciaDesc:
      'Permiten recordar información para que accedas ao servizo con certas características (idioma).',
    cookiesBannerVolver: 'Volver atrás',
    cookiesBannerGuardar: 'Gardar preferencias',
    configTextosLegales: 'Textos Legais',
    configTecnologias:
      'Desenvolto con Next.js, TypeScript, Tailwind CSS, Supabase e Google Gemini.',
    caixaSugerencias: 'Caixa de suxestións',
    caixaSugerenciasSubtitulo: 'Envíanos a túa opinión ou informa de erros',
    caixaPlaceholder: 'Que mellorarías?',
    caixaGracias: 'Grazas!',
    caixaMinimizar: 'Minimizar',
    caixaEnviar: 'Enviar',
    caixaEnviando: 'Enviando...',
    sobreNosotrosTitulo: 'Sobre Nós',
    sobreNosotrosMision: 'A Nosa Misión',
    sobreNosotrosMisionTexto:
      'ImaginAC é unha plataforma educativa deseñada para facilitar a accesibilidade cognitiva a profesores de educación especial e alumnos con necesidades específicas de aprendizaxe.',
    sobreNosotrosPicto: 'Pictogramas e Recursos Visuais',
    sobreNosotrosPictoTexto:
      'Os pictogramas empregados en ImaginAC proveñen do proxecto ARASAAC, distribuídos baixo licenza Creative Commons.',
    atribucionArasaac: 'Atribución ARASAAC',
    atribucionArasaacTexto:
      'Os símbolos pictográficos empregados son propiedade do Goberno de Aragón e foron creados por Sergio Palao para ARASAAC (http://www.arasaac.org), distribuídos baixo Licenza Creative Commons BY-NC-SA.',
    deslindeAragon:
      'O Goberno de Aragón non se fai responsable do uso que terceiros fagan destes materiais.',
    tecnologias: 'Tecnoloxías Utilizadas',
    techNextjs: 'Framework web',
    techTypescript: 'Linguaxe tipada',
    techTailwind: 'Estilos',
    techSupabase: 'Base de datos',
    techGemina: 'Intelixencia Artificial',
    techJsPDF: 'Xeración de PDFs',
    techArasaac: 'Pictogramas (fonte externa)',
    derechosReservados: 'Todos os dereitos reservados.',
    terminosTitulo: 'Termos de Uso',
    terminosAceptacion: '1. Aceptación dos Termos',
    terminosAceptacionTexto:
      'Ao acceder e utilizar a plataforma ImaginAC, vostede acepta estar suxeito a estes Termos de Uso.',
    terminosDescripcion: '2. Descripción do Servizo',
    terminosDescripcionTexto:
      'ImaginAC é unha plataforma educativa que proporciona ferramentas de accesibilidade cognitiva.',
    terminosUsoAceptable: '3. Uso Aceptable',
    terminosUsoTexto: 'O usuario comprométese a:',
    terminosPropiedad: '4. Propiedade Intelectual',
    terminosPropiedadTexto: 'Os pictogramas proveñen de ARASAAC con licenza CC BY-NC-SA.',
    terminosLimitacion: '5. Limitación de Responsabilidade',
    terminosLimitacionTexto: 'ImaginAC proporciónase "tal cual".',
    terminosModificacion: '6. Modificacións',
    terminosModificacionTexto: 'Reservamos o dereito de modificar estes termos.',
    terminosContacto: '7. Contacto',
    terminosContactoTexto: 'Para preguntas sobre estes Termos, póñase en contacto connosco.',
    privacidadTitulo: 'Política de Privacidade',
    privacidadIntro: '1. Introdución',
    privacidadIntroTexto: 'ImaginAC comprométese a protexer a súa privacidade.',
    privacidadDatos: '2. Datos que Recopilamos',
    privacidadUso: '3. Uso dos Datos',
    privacidadUsoTexto: 'Empregamos os seus datos para:',
    privacidadCookies: '4. Cookies',
    privacidadCookiesTexto: 'Empregamos cookies para:',
    privacidadCookiesAdicional: 'Consulte a nosa Política de Cookies.',
    privacidadProteccion: '5. Protección de Datos',
    privacidadProteccionTexto: 'Implementamos medidas de seguridade para protexer os seus datos.',
    privacidadDerechos: '6. Os seus Dereitos',
    privacidadDerechosTexto: 'Vostede ten dereito a:',
    privacidadTerceros: '7. Terceiros',
    privacidadTercerosTexto: 'Non compartimos datos persoais agás cando sexa necesario.',
    privacidadCambios: '8. Cambios',
    privacidadCambiosTexto: 'Podemos actualizar esta política periódicamente.',
    cuentosTitulo: 'Contos Accesibles',
    cuentosDescripcion: 'Crea contos adaptados con pictogramas.',
    cuentosDisponibles: 'Contos Dispoñibles',
    cuentosDisponiblesDesc: 'Inicie sesión para crear e xestionar os seus contos.',
    accederCrear: 'Iniciar sesión para Crear',
    creditosPicto: 'Créditos de Pictogramas',
    autorPicto: 'Autor dos pictogramas:',
    origen: 'Orixe:',
    licencia: 'Licenza:',
    propiedad: 'Propiedade:',
    gobiernoAragon: 'Goberno de Aragón (España)',
    atribucionFooter: 'Autor: Sergio Palao. Orixe: ARASAAC. Licenza: CC BY-NC-SA',
    pictogramas: 'Pictogramas',
    formTituloCuento: 'Título do conto',
    formPlaceholderTitulo: 'O dragón que tiña medo',
    formTematica: 'Temática',
    formSelectTematica: 'Selecciona unha temática',
    formFinalidad: 'Finalidade pedagóxica',
    formPlaceholderFinalidad: 'Este conto axuda ao neno a identificar e expresar o medo.',
    formCaracteres: 'caracteres',
    formLongitud: 'Lonxitude do conto',
    formCorto: 'Curto',
    formMedio: 'Medio',
    formLargo: 'Longo',
    formPalabras: 'palabras',
    formResumen: 'Resumo da xeración',
    formLabelTitulo: 'Título',
    formLabelTematica: 'Temática',
    formLabelIdioma: 'Idioma',
    formLabelLongitud: 'Lonxitude',
    formSinDefinir: 'Sen definir',
    formGenerando: 'Xerando conto...',
    formBotonGenerar: 'Xerar Conto con Pictogramas',
    formPalabras100: '100 palabras',
    formPalabras200: '200 palabras',
    formPalabras300: '300 palabras',
  },
  EU: {
    inicio: 'Hasiera',
    cuentos: 'Ipuinak',
    sobreNosotros: 'Guri Buruz',
    acceder: 'Sartu',
    politicaPrivacidad: 'Pribatutasun Politika',
    terminosUso: 'Erabilera Baldintzak',
    heroTitulo: 'Kognitibo Erabilgarritasuna Denontzat',
    heroSubtitulo: 'HEPrako irakasle eta ikasleentzat diseinatutako hezkuntza-tresnak.',
    accederApp: 'Sartu Aplikaziora',
    copyright: 'Eskubide guztiak erreserbaturik.',
    sobreHistoriaTitulo: 'ImaginAC-en atzean dagoen historia',
    sobreHistoriaSubtitulo: 'Beharrizko premia batetik denontzatako tresna batera',
    sobreHistoriaParrafo1:
      'ImaginAC ez zen bulego batean sortu, baizik eta kafe-egunean. Lagun on bati, etorkizunean Pedagogia Terapeutikoan (PT) espezializatuko zen irakasle bati, frustrazioa partekatzen entzuten nion: pictograma-bankoei esker ere, denbora galtzen zuen bilatzen, mozten eta itsatsiz materialak sortzeko ikasleei egokituak.',
    sobreHistoriaParrafo2:
      'Ez zen leku existitzen kontu bat hutsetik sortzeko eta instantzian inprimatzeko prest dagoen baliabide bihurtzeko. Garatzaile gisa, teknologiak hutsune hori bete behar zuela jakin nuen.',
    sobreHistoriaParrafo3:
      'Nire lagunak horrela sentitzen bazen, milaka irakasek gauza bera jasango zuketen. Gaurko nire misioa sinplea da: zuk imajinazioa jarri eta nik kodea. Elkarrekin, segundotan material inklusibo eta profesionalak sortzen ditugu.',
    sobrePerfilTitulo: 'Kaixo, ni naiz Carmen',
    sobrePerfilDescripcion:
      'Nire izen osoa Carmen Vicente Crespo da. Telekomunikazio Teknologiako Ingeniaritzan ikasketak amaitzean, nire pasioa web garapenari, adimen artifizialari eta zibersegurtasunari eskaini nien.',
    sobrePerfilDescripcion2:
      'ImaginAC ezagutz tekniko hauek helburu sozial batekin konbinatuaren emaitza da: hezkuntza komunitatearen eguneroko bizitza erraztea tresna adimentsuen bidez.',
    sobreContactoTitulo: 'Kontsulta bat duzu?',
    sobreContactoDescripcion:
      'Dudan bat baduzu edo zerbait proposatu nahi baduzu, sakatu botoia idatzizko.',
    sobreContactoBoton: 'Posta bidali',
    enlaces: 'Estekak',
    legal: 'Legala',
    aceptar: 'Onartu',
    avisoCookies: 'Cookieak erabiltzen ditugu zure esperientzia hobetzeko.',
    configTitulo: 'Ezarpenak',
    configIdioma: 'Hizkuntza',
    configIdiomaDesc: 'Hautatu interfazearen hizkuntza. Aldaketa berehala aplikatuko da.',
    configPrivacidad: 'Pribatutasuna',
    configPoliticaPrivacidad: 'Pribatutasun Politika',
    configPoliticaCookies: 'Cookies Politika',
    configAvisoLegal: 'Aviso Legala',
    configTerminos: 'Erabilera Baldintzak',
    configAcerca: 'Honi buruz',
    configDescripcion: 'Irakasle PT eta ikasleentzako kognitibo irisgarritasun plataforma.',
    configPrivacidadTitulo: 'Pribatutasun Hobespenak',
    cookiesAnaliticas: 'Cookie Analitikoak',
    cookiesAnaliticasDesc: 'Toola hobetzen laguntzen dute erabilera anonimoan neurtuz.',
    cookiesPersonalizacion: 'Personifikazio Cookieak',
    cookiesPersonalizacionDesc: 'Hizkuntza eta ezarpenak gogoratzea ahalbidetzen dute.',
    cookiesBannerTexto:
      'Gure eta hirugarrenen cookieak erabiltzen ditugu zure esperientzia hobetzeko eta webaren erabilera analizatzeko. Cookie guztiak onartu, ukatu edo zure lehentasak configure ditzakezu.',
    cookiesBannerConfigurar: 'Konfiguratu',
    cookiesBannerEsenciales: 'Bakarrak beharrezkoak',
    cookiesBannerAceptar: 'Guptiak onartu',
    cookiesBannerPrivacidad: 'Pribatutasun ezarpenak',
    cookiesBannerNecesarias: 'Beharrezkoak',
    cookiesBannerNecesariasDesc:
      'Webaren oinarrizko funtzionamendua ahalbidetzen dute, hala nola nabigazioa eta segurtasuna.',
    cookiesBannerSiempreActivas: 'Beti aktibo',
    cookiesBannerAnaliticas: 'Analitikoak',
    cookiesBannerAnaliticasDesc:
      'Erabiltzaileek webarekin nola elkarreragiten duten ulertzen laguntziguzu modu anonimoan.',
    cookiesBannerPreferencia: 'Lehentasuna',
    cookiesBannerPreferenciaDesc:
      'Zerbitzura sartzeko informazioa gogoratzea ahalbidetzen du zenbait ezaugarrirekin (hizkuntza).',
    cookiesBannerVolver: 'Itzuli',
    cookiesBannerGuardar: 'Gorde lehentasak',
    configTextosLegales: 'Testu Legaleak',
    configTecnologias:
      'Next.js, TypeScript, Tailwind CSS, Supabase eta Google Gemini erabiliz garatua.',
    cajaSugerencias: 'Iradokizun kutxa',
    cajaSugerenciasSubtitulo: 'Bidali zure iritzia edo jakinarazi akatsen bat',
    cajaPlaceholder: 'Zer hobetuko zenuke?',
    cajaGracias: 'Eskerrik asko!',
    cajaMinimizar: 'Minimizatu',
    cajaEnviar: 'Bidali',
    cajaEnviando: 'Bidaltzen...',
    sobreNosotrosTitulo: 'Guri Buruz',
    sobreNosotrosMision: 'Gure Misioa',
    sobreNosotrosMisionTexto:
      'ImaginAC irakasle berezi eta ikasleentzako irisgarritasun kognitiboa errazteko diseinatutako hezkuntza plataforma da.',
    sobreNosotrosPicto: 'Piktogramak eta Baliabide Bisualak',
    sobreNosotrosPictoTexto:
      'ImaginAC-en erabilitako piktogramak ARASAAC proyekttutik datoz, Creative Commons lizentziapean banatuta.',
    atribucionArasaac: 'ARASAAC Atribuzioa',
    atribucionArasaacTexto:
      'Erabilitako piktograma sinboloak Arabako Kontseiluarenak dira eta Sergio Palaok sortu ditu ARASAAC-erako (http://www.arasaac.org), Creative Commons BY-NC-SA lizentziapean banatuta.',
    deslindeAragon:
      'Arabako Kontseilua ez da arduradun material hauek hirugarrenek egiten duten erabileraren gainetik.',
    tecnologias: 'Erabilitako Teknologiak',
    techNextjs: 'Web framework',
    techTypescript: 'Idazketa motako hizkuntza',
    techTailwind: 'Estiloak',
    techSupabase: 'Datu basea',
    techGemina: 'Adimen Artifiziala',
    techJsPDF: 'PDF sorrera',
    techArasaac: 'Piktogramak (kanpo iturria)',
    derechosReservados: 'Eskubide guztiak erreserbaturik.',
    terminosTitulo: 'Erabilera Baldintzak',
    terminosAceptacion: '1. Baldintzak Onartzea',
    terminosAceptacionTexto:
      'ImaginAC plataformara sartzean eta erabiltzean, baldintza hauei lotuta egotea onartzen duzu.',
    terminosDescripcion: '2. Zerbitzuaren Deskribapena',
    terminosDescripcionTexto:
      'ImaginAC irisgarritasun kognitiboko tresnak ematen dituen hezkuntza plataforma da.',
    terminosUsoAceptable: '3. Onargarria den Erabilera',
    terminosUsoTexto: 'Erabiltzaileak honako hauetara konprometitzen da:',
    terminosPropiedad: '4. Jabetza Intelektuala',
    terminosPropiedadTexto: 'Piktogramak ARASAAC-etik datoz CC BY-NC-SA lizentziarekin.',
    terminosLimitacion: '5. Erantzukizunaren Murrizketa',
    terminosLimitacionTexto: 'ImaginAC "bere horretan" ematen da.',
    terminosModificacion: '6. Aldaketak',
    terminosModificacionTexto: 'Baldintza hauek edozein unetan aldatzeko eskubidea dugu.',
    terminosContacto: '7. Kontaktua',
    terminosContactoTexto: 'Baldintzei buruzko galderak badituzu, jar zaitez gurekin harremanetan.',
    privacidadTitulo: 'Pribatutasun Politika',
    privacidadIntro: '1. Sarrera',
    privacidadIntroTexto: 'ImaginAC zure pribatutasuna babestera konprometituta dago.',
    privacidadDatos: '2. Biltzen Ditugun Datuak',
    privacidadUso: '3. Datuen Erabilera',
    privacidadUsoTexto: 'Zure datuak erabiltzen ditugu:',
    privacidadCookies: '4. Cookieak',
    privacidadCookiesTexto: 'Cookieak erabiltzen ditugu:',
    privacidadCookiesAdicional:
      'Cookieei buruzko informazio gehiagorako, ikusi gure Cookie Politika.',
    privacidadProteccion: '5. Datuen Babesa',
    privacidadProteccionTexto:
      'Zure datu pertsonalak babesteko neurri egokiak implementatzen ditugu.',
    privacidadDerechos: '6. Zure Eskubideak',
    privacidadDerechosTexto: 'Zuk eskubidea duzu:',
    privacidadTerceros: '7. Hirugarrenak',
    privacidadTercerosTexto:
      'Ez ditugu datu pertsonalak partekatzen zerbitzua emateko beharrezkoa denean izan ezik.',
    privacidadCambios: '8. Aldaketak',
    privacidadCambiosTexto: 'Politika hau aldizka eguneratu dezakegu.',
    cuentosTitulo: 'Ipuin Iristekoa',
    cuentosDescripcion: 'Sortu piktogramadun ipuin egokituak.',
    cuentosDisponibles: 'Ipuin Iristekoa',
    cuentosDisponiblesDesc: 'Saioa hasi zure ipuin egokituak sortzeko eta kudeatzeko.',
    accederCrear: 'Sortzeko Saioa Hasi',
    creditosPicto: 'Piktograma Kredituak',
    autorPicto: 'Piktograma egilea:',
    origen: 'Jatorria:',
    licencia: 'Lizentzia:',
    propiedad: 'Jabetza:',
    gobiernoAragon: 'Arabako Kontseilua (Espainia)',
    atribucionFooter: 'Egilea: Sergio Palao. Jatorria: ARASAAC. Lizentzia: CC BY-NC-SA',
    pictogramas: 'Piktogramak',
    formTituloCuento: 'Ipuinaren izenburua',
    formPlaceholderTitulo: 'Belarra izan zen beldurrea',
    formTematica: 'Gaiak',
    formSelectTematica: 'Hautatu gai bat',
    formFinalidad: 'Helburu pedagogikoa',
    formPlaceholderFinalidad:
      'Ipuin honek umeari beldurra identifikatzen eta adierazten laguntzen dio.',
    formCaracteres: 'karaktere',
    formLongitud: 'Ipuinaren luzera',
    formCorto: 'Laburra',
    formMedio: 'Ertaina',
    formLargo: 'Luzea',
    formPalabras: 'hitza',
    formResumen: 'Sortzearen laburpena',
    formLabelTitulo: 'Izenburua',
    formLabelTematica: 'Gaia',
    formLabelIdioma: 'Hizkuntza',
    formLabelLongitud: 'Luzera',
    formSinDefinir: 'Zehaztu gabea',
    formGenerando: 'Ipuina sortzen...',
    formBotonGenerar: 'Piktogramadun Ipuina Sortu',
    formPalabras100: '100 hitz',
    formPalabras200: '200 hitz',
    formPalabras300: '300 hitz',
  },
  FR: {
    inicio: 'Accueil',
    cuentos: 'Contes',
    sobreNosotros: 'À Propos',
    acceder: 'Connexion',
    politicaPrivacidad: 'Politique de Confidentialité',
    terminosUso: "Conditions d'Utilisation",
    heroTitulo: 'Accessibilité Cognitive pour Tous',
    heroSubtitulo:
      'Outils éducatifs conçus pour les enseignants ELS et les élèves ayant des besoins spécifiques.',
    accederApp: "Accéder à l'App",
    copyright: 'Tous droits réservés.',
    sobreHistoriaTitulo: "L'histoire derrière ImaginAC",
    sobreHistoriaSubtitulo: "D'un besoin réel à un outil pour tous",
    sobreHistoriaParrafo1:
      "ImaginAC n'est pas né dans un bureau, mais lors d'un après-midi café. J'écoutais une bonne amie, future enseignante spécialisée en Pédagogie thérapeutique (PT), partager sa frustration : malgré d'excellentes banques de pictogrammes, elle perdait du temps à chercher, découpe et coller manuellement pour créer des matériaux adaptés à ses élèves.",
    sobreHistoriaParrafo2:
      "Il n'existait pas d'endroit qui lui permettrait de créer une histoire de zéro et de la transformer, instantanément, en ressource visuelle prête à imprimir. En tant que développeur, j'ai su que la technologie devait combler ce vide.",
    sobreHistoriaParrafo3:
      "Si mon ami se sentait ainsi, des milliers d'enseignants vivraient la même chose. Ma mission aujourd'hui est simple : vous fournissez l'imagination et je fournis le code. Ensemble, nous créons des matériaux inclusifs et professionnels en quelques secondes.",
    sobrePerfilTitulo: 'Bonjour, je suis Carmen',
    sobrePerfilDescripcion:
      "Mon nom complet est Carmen Vicente Crespo. Après avoir terminé ma formation en Ingénierie des Technologies de Télécommunication, j'ai décidé de consacrer ma passion au développement web, à l'intelligence artificielle et à la cybersécurité.",
    sobrePerfilDescripcion2:
      'ImaginAC est le résultat de la combinaison de ces connaissances techniques avec un but social : faciliter le quotidien de la communauté éducative grâce à des outils intelligents.',
    sobreContactoTitulo: 'Vous avez une question?',
    sobreContactoDescripcion:
      "Si vous avez des doutes ou voulez proposer quelque chose, appuyez sur le bouton pour m'écrire.",
    sobreContactoBoton: 'Envoyer un email',
    enlaces: 'Liens',
    legal: 'Légal',
    aceptar: 'Accepter',
    avisoCookies: 'Nous utilisons des cookies pour améliorer votre expérience.',
    configTitulo: 'Paramètres',
    configIdioma: 'Langue',
    configIdiomaDesc:
      "Sélectionnez la langue de l'interface. Les modifications s'appliquent immédiatement.",
    configPrivacidad: 'Confidentialité',
    configPoliticaPrivacidad: 'Politique de Confidentialité',
    configPoliticaCookies: 'Politique de Cookies',
    configAvisoLegal: 'Aviso Légal',
    configTerminos: "Conditions d'Utilisation",
    configAcerca: 'À propos',
    configDescripcion: "Plateforme d'accessibilité cognitive pour enseignants ELS et élèves.",
    configPrivacidadTitulo: 'Préférences de Confidentialité',
    cookiesAnaliticas: 'Cookies Analytiques',
    cookiesAnaliticasDesc: "Aident à améliorer l'outil en mesurant utilisation de manière anonyme.",
    cookiesPersonalizacion: 'Cookies de Personnalisation',
    cookiesPersonalizacionDesc:
      'Permettent de mémoriser langue et paramètres pour prochaine visite.',
    cookiesBannerTexto:
      "Nous utilisons des cookies propres et tiers pour améliorer votre expérience et analyser l'utilisation du site. Vous pouvez accepter tous les cookies, les refuser ou configurer vos préférences.",
    cookiesBannerConfigurar: 'Configurer',
    cookiesBannerEsenciales: 'Essentiels uniquement',
    cookiesBannerAceptar: 'Tout accepter',
    cookiesBannerPrivacidad: 'Paramètres de confidentialité',
    cookiesBannerNecesarias: 'Nécessaires',
    cookiesBannerNecesariasDesc:
      'Elles permettent le fonctionnement de base du site comme la navigation et la sécurité.',
    cookiesBannerSiempreActivas: 'Toujours actives',
    cookiesBannerAnaliticas: 'Analytiques',
    cookiesBannerAnaliticasDesc:
      'Elles nous aident à comprendre comment les utilisateurs interagissent avec le site de manière anonyme.',
    cookiesBannerPreferencia: 'Préférence',
    cookiesBannerPreferenciaDesc:
      'Permettent de mémoriser des informations pour accéder au service avec certaines caractéristiques (langue).',
    cookiesBannerVolver: 'Retour',
    cookiesBannerGuardar: 'Enregistrer les préférences',
    configTextosLegales: 'Textes Légaux',
    configTecnologias:
      'Développé avec Next.js, TypeScript, Tailwind CSS, Supabase et Google Gemini.',
    cajaSugerencias: 'Boîte à suggestions',
    cajaSugerenciasSubtitulo: 'Envoyez-nous vos commentaires ou signalez des erreurs',
    cajaPlaceholder: 'Que changeriez-vous?',
    cajaGracias: 'Merci!',
    cajaMinimizar: 'Réduire',
    cajaEnviar: 'Envoyer',
    cajaEnviando: 'Envoi en cours...',
    sobreNosotrosTitulo: 'À Propos',
    sobreNosotrosMision: 'Notre Mission',
    sobreNosotrosMisionTexto:
      "ImaginAC est une plateforme éducative conçue pour faciliter l'accessibilité cognitive pour les enseignants de l'éducation spéciale et les élèves ayant des besoins d'apprentissage spécifiques.",
    sobreNosotrosPicto: 'Pictogrammes et Ressources Visuelles',
    sobreNosotrosPictoTexto:
      'Les pictogrammes utilisés dans ImaginAC proviennent du projet ARASAAC, distribués sous licence Creative Commons.',
    atribucionArasaac: 'Attribution ARASAAC',
    atribucionArasaacTexto:
      "Les symboles pictographiques utilisés sont la propriété du Gouvernement d'Aragon et ont été créés par Sergio Palao pour ARASAAC (http://www.arasaac.org), distribués sous licence Creative Commons BY-NC-SA.",
    deslindeAragon:
      "Le Gouvernement d'Aragon n'est pas responsable de l'utilisation que des tiers font de ces matériaux.",
    tecnologias: 'Technologies Utilisées',
    techNextjs: 'Framework web',
    techTypescript: 'Langage typé',
    techTailwind: 'Styles',
    techSupabase: 'Base de données',
    techGemina: 'Intelligence Artificielle',
    techJsPDF: 'Génération de PDFs',
    techArasaac: 'Pictogrammes (source externe)',
    derechosReservados: 'Tous droits réservés.',
    terminosTitulo: "Conditions d'Utilisation",
    terminosAceptacion: '1. Acceptation des Conditions',
    terminosAceptacionTexto:
      "En accédant et utilisant la plateforme ImaginAC, vous acceptez d'être lié par ces Conditions d'Utilisation.",
    terminosDescripcion: '2. Description du Service',
    terminosDescripcionTexto:
      "ImaginAC est une plateforme éducative fournissant des outils d'accessibilité cognitive.",
    terminosUsoAceptable: '3. Utilisation Acceptable',
    terminosUsoTexto: "L'utilisateur s'engage à:",
    terminosPropiedad: '4. Propriété Intellectuelle',
    terminosPropiedadTexto: "Les pictogrammes proviennent d'ARASAAC sous licence CC BY-NC-SA.",
    terminosLimitacion: '5. Limitation de Responsabilité',
    terminosLimitacionTexto: 'ImaginAC est fourni "tel quel".',
    terminosModificacion: '6. Modifications',
    terminosModificacionTexto: 'Nous nous réservons le droit de modifier ces conditions.',
    terminosContacto: '7. Contact',
    terminosContactoTexto: 'Pour toute question, contactez-nous via la plateforme.',
    privacidadTitulo: 'Politique de Confidentialité',
    privacidadIntro: '1. Introduction',
    privacidadIntroTexto: "ImaginAC s'engage à protéger votre vie privée.",
    privacidadDatos: '2. Données que Nous Collectons',
    privacidadUso: '3. Utilisation des Données',
    privacidadUsoTexto: 'Nous utilisons vos données pour:',
    privacidadCookies: '4. Cookies',
    privacidadCookiesTexto: 'Nous utilisons des cookies pour:',
    privacidadCookiesAdicional: "Pour plus d'informations, consultez notre Politique de Cookies.",
    privacidadProteccion: '5. Protection des Données',
    privacidadProteccionTexto: 'Nous mettons en place des mesures de sécurité appropriées.',
    privacidadDerechos: '6. Vos Droits',
    privacidadDerechosTexto: 'Vous avez le droit de:',
    privacidadTerceros: '7. Tiers',
    privacidadTercerosTexto: 'Nous ne partageons pas de données personnelles sauf si nécessaire.',
    privacidadCambios: '8. Changements',
    privacidadCambiosTexto: 'Nous pouvons mettre à jour cette politique périodiquement.',
    cuentosTitulo: 'Contes Accessibles',
    cuentosDescripcion: 'Créez des contes adaptés avec des pictogrammes.',
    cuentosDisponibles: 'Contes Disponibles',
    cuentosDisponiblesDesc: 'Connectez-vous pour créer et gérer vos contes.',
    accederCrear: 'Se connecter pour Créer',
    creditosPicto: 'Crédits Pictogrammes',
    autorPicto: 'Auteur des pictogrammes:',
    origen: 'Origine:',
    licencia: 'Licence:',
    propiedad: 'Propriété:',
    gobiernoAragon: "Gouvernement d'Aragon (Espagne)",
    atribucionFooter: 'Auteur: Sergio Palao. Origine: ARASAAC. Licence: CC BY-NC-SA',
    pictogramas: 'Pictogrammes',
    formTituloCuento: 'Titre du conte',
    formPlaceholderTitulo: 'Le dragon qui avait peur',
    formTematica: 'Thème',
    formSelectTematica: 'Sélectionnez un thème',
    formFinalidad: 'Objectif pédagogique',
    formPlaceholderFinalidad: "Ce conte aide l'enfant à identifier et exprimer la peur.",
    formCaracteres: 'caractères',
    formLongitud: 'Longueur du conte',
    formCorto: 'Court',
    formMedio: 'Moyen',
    formLargo: 'Long',
    formPalabras: 'mots',
    formResumen: 'Résumé de la génération',
    formLabelTitulo: 'Titre',
    formLabelTematica: 'Thème',
    formLabelIdioma: 'Langue',
    formLabelLongitud: 'Longueur',
    formSinDefinir: 'Non défini',
    formGenerando: 'Génération en cours...',
    formBotonGenerar: 'Générer un Conte avec Pictogrammes',
    formPalabras100: '100 mots',
    formPalabras200: '200 mots',
    formPalabras300: '300 mots',
  },
  DE: {
    inicio: 'Startseite',
    cuentos: 'Geschichten',
    sobreNosotros: 'Über Uns',
    acceder: 'Anmelden',
    politicaPrivacidad: 'Datenschutzrichtlinie',
    terminosUso: 'Nutzungsbedingungen',
    heroTitulo: 'Kognitive Barrierefreiheit für Alle',
    heroSubtitulo: 'Bildungstools für Sonderpädagogen und Schüler mit spezifischem Lernbedarf.',
    accederApp: 'Zur App',
    copyright: 'Alle Rechte vorbehalten.',
    sobreHistoriaTitulo: 'Die Geschichte hinter ImaginAC',
    sobreHistoriaSubtitulo: 'Von einem echten Bedarf zu einem Werkzeug für alle',
    sobreHistoriaParrafo1:
      'ImaginAC wurde nicht in einem Büro geboren, sondern bei einem Kaffee-Nachmittag. Ich hörte einer guten Freundin zu, einer zukünftigen Sonderpädagogin (PT), die ihre Frustration teilte: Trotz exzellenter Pictogramm-Banken verlor sie Zeit mit dem Suchen, Ausschneiden und manuellen Kleben, um Materialien für ihre Schüler zu erstellen.',
    sobreHistoriaParrafo2:
      'Es gab keinen Ort, der es ihr ermöglichen würde, eine Geschichte von Grund auf zu erstellen und sie sofort in eine druckfertige visuelle Ressource zu verwandeln. Als Entwicklerin wusste ich, dass diese Lücke von der Technologie gefüllt werden musste.',
    sobreHistoriaParrafo3:
      'Wenn meine Freundin sich so fühlte, würden Tausende von Lehrern das Gleiche erleben. Meine Mission heute ist einfach: Sie liefern die Vorstellungskraft und ich den Code. Zusammen erstellen wir in Sekunden inklusive und professionelle Materialien.',
    sobrePerfilTitulo: 'Hallo, ich bin Carmen',
    sobrePerfilDescripcion:
      'Mein vollständiger Name ist Carmen Vicente Crespo. Nach Abschluss meiner Ausbildung in Telekommunikationstechnologie beschloss ich, meine Leidenschaft der Webentwicklung, künstlichen Intelligenz und Cybersicherheit zu widmen.',
    sobrePerfilDescripcion2:
      'ImaginAC ist das Ergebnis der Kombination dieser technischen Kenntnisse mit einem sozialen Ziel: die Erleichterung des Alltags der Bildungsgemeinschaft durch intelligente Werkzeuge.',
    sobreContactoTitulo: 'Haben Sie eine Frage?',
    sobreContactoDescripcion:
      'Wenn Sie Zweifel haben oder etwas vorschlagen möchten, klicken Sie auf die Schaltfläche, um mir zu schreiben.',
    sobreContactoBoton: 'E-Mail senden',
    enlaces: 'Links',
    legal: 'Rechtliches',
    aceptar: 'Akzeptieren',
    avisoCookies: 'Wir verwenden Cookies, um Ihre Erfahrung zu verbessern.',
    configTitulo: 'Einstellungen',
    configIdioma: 'Sprache',
    configIdiomaDesc:
      'Wählen Sie die Sprache der Oberfläche. Die Änderungen werden sofort angewendet.',
    configPrivacidad: 'Datenschutz',
    configPoliticaPrivacidad: 'Datenschutzrichtlinie',
    configPoliticaCookies: 'Cookie-Richtlinie',
    configAvisoLegal: 'Impressum',
    configTerminos: 'Nutzungsbedingungen',
    configAcerca: 'Über',
    configDescripcion:
      'Plattform für kognitive Barrierefreiheit für Sonderschullehrer und Schüler.',
    configPrivacidadTitulo: 'Datenschutz-Einstellungen',
    cookiesAnaliticas: 'Analyse-Cookies',
    cookiesAnaliticasDesc: 'Helfen beim Verbessern des Tools durch anonyme Nutzungsmessung.',
    cookiesPersonalizacion: 'Personalisierungs-Cookies',
    cookiesPersonalizacionDesc:
      'Ermöglichen Speichern von Sprache und Einstellungen für nächsten Besuch.',
    cookiesBannerTexto:
      'Wir verwenden eigene und Drittanbieter-Cookies, um Ihr Erlebnis zu verbessern und die Websitenutzung zu analysieren. Sie können alle Cookies akzeptieren, ablehnen oder Ihre Einstellungen konfigurieren.',
    cookiesBannerConfigurar: 'Konfigurieren',
    cookiesBannerEsenciales: 'Nur essenzielle',
    cookiesBannerAceptar: 'Alle akzeptieren',
    cookiesBannerPrivacidad: 'Datenschutzeinstellungen',
    cookiesBannerNecesarias: 'Notwendige',
    cookiesBannerNecesariasDesc:
      'Sie ermöglichen das grundlegende Funktionieren der Webseite wie Navigation und Sicherheit.',
    cookiesBannerSiempreActivas: 'Immer aktiv',
    cookiesBannerAnaliticas: 'Analyse',
    cookiesBannerAnaliticasDesc:
      'Sie helfen uns zu verstehen, wie Nutzer anonym mit der Webseite interagieren.',
    cookiesBannerPreferencia: 'Präferenz',
    cookiesBannerPreferenciaDesc:
      'Sie ermöglichen das Speichern von Informationen, damit Sie mit bestimmten Funktionen auf den Dienst zugreifen können (Sprache).',
    cookiesBannerVolver: 'Zurück',
    cookiesBannerGuardar: 'Einstellungen speichern',
    configTextosLegales: 'Rechtliche Texte',
    configTecnologias:
      'Entwickelt mit Next.js, TypeScript, Tailwind CSS, Supabase und Google Gemini.',
    cajaSugerencias: 'Vorschlagsbox',
    cajaSugerenciasSubtitulo: 'Senden Sie uns Ihr Feedback oder melden Sie Fehler',
    cajaPlaceholder: 'Was würden Sie verbessern?',
    cajaGracias: 'Danke!',
    cajaMinimizar: 'Minimieren',
    cajaEnviar: 'Senden',
    cajaEnviando: 'Wird gesendet...',
    sobreNosotrosTitulo: 'Über Uns',
    sobreNosotrosMision: 'Unsere Mission',
    sobreNosotrosMisionTexto:
      'ImaginAC ist eine Bildungsplattform, die entwickelt wurde, um kognitive Barrierefreiheit für Sonderschullehrer und Schüler mit spezifischen Lernbedürfnissen zu erleichtern.',
    sobreNosotrosPicto: 'Piktogramme und visuelle Ressourcen',
    sobreNosotrosPictoTexto:
      'Die in ImaginAC verwendeten Piktogramme stammen aus dem ARASAAC-Projekt und werden unter Creative Commons-Lizenz vertrieben.',
    atribucionArasaac: 'ARASAAC-Zuschreibung',
    atribucionArasaacTexto:
      'Die verwendeten piktografischen Symbole sind Eigentum der Regierung von Aragonien und wurden von Sergio Palao für ARASAAC (http://www.arasaac.org) erstellt, vertrieben unter Creative Commons BY-NC-SA-Lizenz.',
    deslindeAragon:
      'Die Regierung von Aragonien ist nicht verantwortlich für die Nutzung dieser Materialien durch Dritte.',
    tecnologias: 'Verwendete Technologien',
    techNextjs: 'Web-Framework',
    techTypescript: 'Typsprache',
    techTailwind: 'Stile',
    techSupabase: 'Datenbank',
    techGemina: 'Künstliche Intelligenz',
    techJsPDF: 'PDF-Erstellung',
    techArasaac: 'Piktogramme (externe Quelle)',
    derechosReservados: 'Alle Rechte vorbehalten.',
    terminosTitulo: 'Nutzungsbedingungen',
    terminosAceptacion: '1. Annahme der Bedingungen',
    terminosAceptacionTexto:
      'Mit dem Zugriff auf und der Nutzung der ImaginAC-Plattform stimmen Sie diesen Nutzungsbedingungen zu.',
    terminosDescripcion: '2. Servicebeschreibung',
    terminosDescripcionTexto:
      'ImaginAC ist eine Bildungsplattform, die kognitive Barrierefreiheitstools bereitstellt.',
    terminosUsoAceptable: '3. Akzeptable Nutzung',
    terminosUsoTexto: 'Der Benutzer verpflichtet sich zu:',
    terminosPropiedad: '4. Geistiges Eigentum',
    terminosPropiedadTexto: 'Die Piktogramme stammen von ARASAAC unter CC BY-NC-SA-Lizenz.',
    terminosLimitacion: '5. Haftungsbeschränkung',
    terminosLimitacionTexto: 'ImaginAC wird "wie besehen" bereitgestellt.',
    terminosModificacion: '6. Änderungen',
    terminosModificacionTexto:
      'Wir behalten uns das Recht vor, diese Bedingungen jederzeit zu ändern.',
    terminosContacto: '7. Kontakt',
    terminosContactoTexto:
      'Bei Fragen zu diesen Bedingungen kontaktieren Sie uns über die Plattform.',
    privacidadTitulo: 'Datenschutzrichtlinie',
    privacidadIntro: '1. Einleitung',
    privacidadIntroTexto: 'ImaginAC verpflichtet sich, Ihre Privatsphäre zu schützen.',
    privacidadDatos: '2. Gesammelte Daten',
    privacidadUso: '3. Datennutzung',
    privacidadUsoTexto: 'Wir verwenden Ihre Daten für:',
    privacidadCookies: '4. Cookies',
    privacidadCookiesTexto: 'Wir verwenden Cookies für:',
    privacidadCookiesAdicional: 'Weitere Informationen finden Sie in unserer Cookie-Richtlinie.',
    privacidadProteccion: '5. Datenschutz',
    privacidadProteccionTexto: 'Wir implementieren geeignete Sicherheitsmaßnahmen.',
    privacidadDerechos: '6. Ihre Rechte',
    privacidadDerechosTexto: 'Sie haben das Recht auf:',
    privacidadTerceros: '7. Dritte',
    privacidadTercerosTexto: 'Wir teilen persönliche Daten nur bei Bedarf.',
    privacidadCambios: '8. Änderungen',
    privacidadCambiosTexto: 'Wir können diese Richtlinie periodisch aktualisieren.',
    cuentosTitulo: 'Zugängliche Geschichten',
    cuentosDescripcion: 'Erstellen Sie angepasste Geschichten mit Piktogrammen.',
    cuentosDisponibles: 'Verfügbare Geschichten',
    cuentosDisponiblesDesc:
      'Melden Sie sich an, um Ihre Geschichten zu erstellen und zu verwalten.',
    accederCrear: 'Anmelden zum Erstellen',
    creditosPicto: 'Piktogramm-Credits',
    autorPicto: 'Piktogramm-Autor:',
    origen: 'Herkunft:',
    licencia: 'Lizenz:',
    propiedad: 'Eigentum:',
    gobiernoAragon: 'Regierung von Aragonien (Spanien)',
    atribucionFooter: 'Autor: Sergio Palao. Herkunft: ARASAAC. Lizenz: CC BY-NC-SA',
    pictogramas: 'Piktogramme',
    formTituloCuento: 'Geschichtstitel',
    formPlaceholderTitulo: 'Der Drache, der Angst hatte',
    formTematica: 'Thema',
    formSelectTematica: 'Wählen Sie ein Thema',
    formFinalidad: 'Pädagogisches Ziel',
    formPlaceholderFinalidad:
      'Diese Geschichte hilft dem Kind, Angst zu identifizieren und auszudrücken.',
    formCaracteres: 'Zeichen',
    formLongitud: 'Geschichte Länge',
    formCorto: 'Kurz',
    formMedio: 'Mittel',
    formLargo: 'Lang',
    formPalabras: 'Wörter',
    formResumen: 'Zusammenfassung der Generierung',
    formLabelTitulo: 'Titel',
    formLabelTematica: 'Thema',
    formLabelIdioma: 'Sprache',
    formLabelLongitud: 'Länge',
    formSinDefinir: 'Nicht definiert',
    formGenerando: 'Geschichte wird generiert...',
    formBotonGenerar: 'Geschichte mit Piktogrammen generieren',
    formPalabras100: '100 Wörter',
    formPalabras200: '200 Wörter',
    formPalabras300: '300 Wörter',
  },
  IT: {
    inicio: 'Home',
    cuentos: 'Racconti',
    sobreNosotros: 'Chi Siamo',
    acceder: 'Accedi',
    politicaPrivacidad: 'Informativa sulla Privacy',
    terminosUso: 'Termini di Utilizzo',
    heroTitulo: 'Accessibilità Cognitiva per Tutti',
    heroSubtitulo:
      'Strumenti educativi per insegnanti di sostegno e alunni con bisogni educativi speciali.',
    accederApp: "Accedi all'App",
    copyright: 'Tutti i diritti riservati.',
    sobreHistoriaTitulo: 'La storia dietro ImaginAC',
    sobreHistoriaSubtitulo: 'Da un bisogno reale a uno strumento per tutti',
    sobreHistoriaParrafo1:
      'ImaginAC non è nato in un ufficio, ma durante un pomeriggio di caffè. Ascoltavo una buona amica, futura insegnante specializzata in Pedagogia Terapeutica (PT), condividere la sua frustrazione: nonostante eccellenti banche di pictogrammi, perdeva tempo cercando, ritagliando e incollando manualmente per creare materiali adatti ai suoi alunni.',
    sobreHistoriaParrafo2:
      "Non esisteva un posto che le permettesse di creare una storia da zero e trasformarla, all'istante, in una risorsa visiva pronta da stampare. Come sviluppatrice, sapevo che la tecnologia doveva colmare quel vuoto.",
    sobreHistoriaParrafo3:
      "Se la mia amica si sentiva così, migliaia di insegnanti vivrebbero la stessa cosa. La mia missione oggi è semplice: tu metti l'immaginazione e io il codice. Insieme creiamo materiali inclusivi e professionali in pochi secondi.",
    sobrePerfilTitulo: 'Ciao, sono Carmen',
    sobrePerfilDescripcion:
      "Mi chiamo Carmen Vicente Crespo. Dopo aver completato la mia formazione in Ingegneria delle Tecnologie delle Telecomunicazioni, ho deciso di dedicare la mia passione allo sviluppo web, all'intelligenza artificiale e alla cibersicurezza.",
    sobrePerfilDescripcion2:
      'ImaginAC è il risultato della combinazione di queste conoscenze tecniche con un obiettivo sociale: facilitare il quotidiano della comunità educativa attraverso strumenti intelligenti.',
    sobreContactoTitulo: 'Hai una domanda?',
    sobreContactoDescripcion:
      'Se hai dubbi o vuoi proporre qualcosa, premi il pulsante per scrivermi.',
    sobreContactoBoton: 'Invia email',
    enlaces: 'Link',
    legal: 'Legale',
    aceptar: 'Accetta',
    avisoCookies: 'Utilizziamo i cookie per migliorare la tua esperienza.',
    configTitulo: 'Impostazioni',
    configIdioma: 'Lingua',
    configIdiomaDesc:
      "Seleziona la lingua dell'interfaccia. Le modifiche si applicano immediatamente.",
    configPrivacidad: 'Privacy',
    configPoliticaPrivacidad: 'Informativa sulla Privacy',
    configPoliticaCookies: 'Informativa sui Cookie',
    configAvisoLegal: 'Avviso Legale',
    configTerminos: 'Termini di Utilizzo',
    configAcerca: 'Info',
    configDescripcion:
      'Piattaforma di accessibilità cognitiva per insegnanti di sostegno e alunni.',
    configPrivacidadTitulo: 'Preferenze Privacy',
    cookiesAnaliticas: 'Cookie Analitici',
    cookiesAnaliticasDesc: "Aiutano a migliorare lo strumento misurando l'uso in modo anonimo.",
    cookiesPersonalizacion: 'Cookie di Personalizzazione',
    cookiesPersonalizacionDesc:
      'Permettono di ricordare lingua e impostazioni per la prossima visita.',
    cookiesBannerTexto:
      "Utilizziamo cookie propri e di terze parti per migliorare la tua esperienza e analizzare l'uso del sito. Puoi accettare tutti i cookie, rifiutarli o configurare le tue preferenze.",
    cookiesBannerConfigurar: 'Configura',
    cookiesBannerEsenciales: 'Solo essenziali',
    cookiesBannerAceptar: 'Accetta tutto',
    cookiesBannerPrivacidad: 'Impostazioni Privacy',
    cookiesBannerNecesarias: 'Necessarie',
    cookiesBannerNecesariasDesc:
      'Permettono il funzionamento base del sito come la navigazione e la sicurezza.',
    cookiesBannerSiempreActivas: 'Sempre attive',
    cookiesBannerAnaliticas: 'Analitiche',
    cookiesBannerAnaliticasDesc:
      'Ci aiutano a capire come gli utenti interagiscono con il sito in modo anonimo.',
    cookiesBannerPreferencia: 'Preferenza',
    cookiesBannerPreferenciaDesc:
      'Permettono di ricordare informazioni per accedere al servizio con determinate caratteristiche (lingua).',
    cookiesBannerVolver: 'Indietro',
    cookiesBannerGuardar: 'Salva preferenze',
    configTextosLegales: 'Testi Legali',
    configTecnologias:
      'Sviluppato con Next.js, TypeScript, Tailwind CSS, Supabase e Google Gemini.',
    cajaSugerencias: 'Casella suggerimenti',
    cajaSugerenciasSubtitulo: 'Inviaci il tuo feedback o segnala errori',
    cajaPlaceholder: 'Cosa miglioreresti?',
    cajaGracias: 'Grazie!',
    cajaMinimizar: 'Minimizza',
    cajaEnviar: 'Invia',
    cajaEnviando: 'Invio in corso...',
    sobreNosotrosTitulo: 'Chi Siamo',
    sobreNosotrosMision: 'La Nostra Missione',
    sobreNosotrosMisionTexto:
      "ImaginAC è una piattaforma educativa progettata per facilitare l'accessibilità cognitiva per insegnanti di educazione speciale e alunni con bisogni specifici di apprendimento.",
    sobreNosotrosPicto: 'Pittogrammi e Risorse Visive',
    sobreNosotrosPictoTexto:
      'I pittogrammi utilizzati in ImaginAC provengono dal progetto ARASAAC, distribuiti con licenza Creative Commons.',
    atribucionArasaac: 'Attribuzione ARASAAC',
    atribucionArasaacTexto:
      'I simboli pittografici utilizzati sono di proprietà del Governo di Aragona e sono stati creati da Sergio Palao per ARASAAC (http://www.arasaac.org), distribuiti con licenza Creative Commons BY-NC-SA.',
    deslindeAragon:
      "Il Governo di Aragona non è responsabile dell'uso che terzi fanno di questi materiali.",
    tecnologias: 'Tecnologie Utilizzate',
    techNextjs: 'Framework web',
    techTypescript: 'Linguaggio tipizzato',
    techTailwind: 'Stili',
    techSupabase: 'Database',
    techGemina: 'Intelligenza Artificiale',
    techJsPDF: 'Generazione PDF',
    techArasaac: 'Pittogrammi (fonte esterna)',
    derechosReservados: 'Tutti i diritti riservati.',
    terminosTitulo: 'Termini di Utilizzo',
    terminosAceptacion: '1. Accettazione dei Termini',
    terminosAceptacionTexto:
      'Accedendo e utilizzando la piattaforma ImaginAC, accetti di essere vincolato da questi Termini di Utilizzo.',
    terminosDescripcion: '2. Descrizione del Servizio',
    terminosDescripcionTexto:
      'ImaginAC è una piattaforma educativa che fornisce strumenti di accessibilità cognitiva, inclusa la generazione di racconti e attività adattate.',
    terminosUsoAceptable: '3. Uso Accettabile',
    terminosUsoTexto: "L'utente si impegna a:",
    terminosPropiedad: '4. Proprietà Intellettuale',
    terminosPropiedadTexto:
      'I racconti e i materiali generati possono essere utilizzati per scopi educativi. I pittogrammi provengono da ARASAAC con licenza CC BY-NC-SA.',
    terminosLimitacion: '5. Limitazione di Responsabilità',
    terminosLimitacionTexto:
      'ImaginAC è fornito "così com\'è". Non siamo responsabili per danni derivanti dall\'uso della piattaforma.',
    terminosModificacion: '6. Modifiche',
    terminosModificacionTexto:
      'Ci riserviamo il diritto di modificare questi termini in qualsiasi momento.',
    terminosContacto: '7. Contatto',
    terminosContactoTexto: 'Per domande su questi termini, contattaci attraverso la piattaforma.',
    privacidadTitulo: 'Informativa sulla Privacy',
    privacidadIntro: '1. Introduzione',
    privacidadIntroTexto:
      'ImaginAC si impegna a proteggere la tua privacy. Questa informativa spiega come raccogliamo, utilizziamo e proteggiamo le tue informazioni personali.',
    privacidadDatos: '2. Dati che Raccogliamo',
    privacidadUso: '3. Uso dei Dati',
    privacidadUsoTexto: 'Utilizziamo i tuoi dati per:',
    privacidadCookies: '4. Cookie',
    privacidadCookiesTexto: 'Utilizziamo i cookie per:',
    privacidadCookiesAdicional:
      'Per ulteriori informazioni sui cookie, consulta la nostra Politica sui Cookie.',
    privacidadProteccion: '5. Protezione dei Dati',
    privacidadProteccionTexto:
      'Implementiamo misure di sicurezza appropriate per proteggere i tuoi dati personali.',
    privacidadDerechos: '6. I Tuoi Diritti',
    privacidadDerechosTexto: 'Hai il diritto di:',
    privacidadTerceros: '7. Terze Parti',
    privacidadTercerosTexto:
      'Non condividiamo dati personali se non quando necessario per fornire il servizio.',
    privacidadCambios: '8. Modifiche',
    privacidadCambiosTexto: 'Potremmo aggiornare periodicamente questa informativa.',
    cuentosTitulo: 'Racconti Accessibili',
    cuentosDescripcion: 'Crea racconti adattati con pittogrammi.',
    cuentosDisponibles: 'Racconti Disponibili',
    cuentosDisponiblesDesc: 'Accedi per creare e gestire i tuoi racconti adattati.',
    accederCrear: 'Accedi per Creare',
    creditosPicto: 'Crediti Pittogrammi',
    autorPicto: 'Autore pittogrammi:',
    origen: 'Origine:',
    licencia: 'Licenza:',
    propiedad: 'Proprietà:',
    gobiernoAragon: 'Governo di Aragona (Spagna)',
    atribucionFooter: 'Autore: Sergio Palao. Origine: ARASAAC. Licenza: CC BY-NC-SA',
    pictogramas: 'Pittogrammi',
    formTituloCuento: 'Titolo del racconto',
    formPlaceholderTitulo: 'Il drago che aveva paura',
    formTematica: 'Tema',
    formSelectTematica: 'Seleziona un tema',
    formFinalidad: 'Finalità pedagogica',
    formPlaceholderFinalidad:
      'Questa storia aiuta il bambino a identificare ed esprimere la paura, promuovendo la comprensione che è normale avere paura.',
    formCaracteres: 'caratteri',
    formLongitud: 'Lunghezza del racconto',
    formCorto: 'Corto',
    formMedio: 'Medio',
    formLargo: 'Lungo',
    formPalabras: 'parole',
    formResumen: 'Riepilogo generazione',
    formLabelTitulo: 'Titolo',
    formLabelTematica: 'Tema',
    formLabelIdioma: 'Lingua',
    formLabelLongitud: 'Lunghezza',
    formSinDefinir: 'Non definito',
    formGenerando: 'Generazione in corso...',
    formBotonGenerar: 'Genera Racconto con Pittogrammi',
    formPalabras100: '100 parole',
    formPalabras200: '200 parole',
    formPalabras300: '300 parole',
  },
};

export function t(clave: string): string {
  const estado = useLanguageStore.getState();
  const codigo = estado.idiomaActual;
  return traduccionesUI[codigo]?.[clave] || traduccionesUI['ES'][clave] || clave;
}
